# Generated by Django 4.2.27 on 2026-06-21 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, verbose_name='연월(YYYY-MM)')),
                ('target_meetings', models.PositiveIntegerField(default=0, verbose_name='만날 고객 수 목표')),
                ('target_premium', models.PositiveBigIntegerField(default=0, verbose_name='월 가입 보험료 목표')),
                ('target_income', models.PositiveBigIntegerField(default=0, verbose_name='예상 월급(수동)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
            ],
            options={
                'verbose_name': '월별 목표',
                'verbose_name_plural': '월별 목표',
                'db_table': 'monthly_goal',
                'indexes': [models.Index(fields=['owner', 'year_month'], name='monthly_goa_owner_i_f12246_idx')],
                'unique_together': {('owner', 'year_month')},
            },
        ),
    ]
