# Generated by Django 4.2.27 on 2026-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlygoal',
            name='target_income',
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='income_multiplier',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5, verbose_name='예상 월급 배율'),
        ),
    ]
