# Generated by Django 5.2 on 2026-07-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTalkTemplate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'source_key',
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name='기본 화법 출처 키',
                    ),
                ),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('body', models.TextField(max_length=5000, verbose_name='본문')),
                (
                    'category',
                    models.CharField(max_length=40, verbose_name='분류'),
                ),
                (
                    'channel',
                    models.CharField(
                        choices=[('message', '메시지'), ('call', '통화')],
                        max_length=20,
                        verbose_name='채널',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(default=0, verbose_name='정렬 순서'),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='personal_talk_templates',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='설계사(소유자)',
                    ),
                ),
            ],
            options={
                'verbose_name': '개인 화법 템플릿',
                'verbose_name_plural': '개인 화법 템플릿',
                'db_table': 'talks_personal_template',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TalkTemplatePreference',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'source_key',
                    models.CharField(
                        max_length=80,
                        verbose_name='기본 화법 출처 키',
                    ),
                ),
                ('is_hidden', models.BooleanField(default=False, verbose_name='숨김')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='talk_template_preferences',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='설계사(소유자)',
                    ),
                ),
            ],
            options={
                'verbose_name': '기본 화법 선호',
                'verbose_name_plural': '기본 화법 선호',
                'db_table': 'talks_template_preference',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('owner', 'source_key'),
                        name='talk_pref_owner_source_uniq',
                    ),
                ],
            },
        ),
    ]
