# Generated by Django 4.2.27 on 2026-06-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('tos', '이용약관'), ('pp', '개인정보처리방침'), ('overseas', '국외이전 동의')], db_index=True, max_length=20)),
                ('version', models.CharField(help_text='예: 2026-06-20 / v2.1', max_length=50)),
                ('effective_at', models.DateTimeField(help_text='시행일시 (UTC)')),
                ('requires_reconsent', models.BooleanField(default=False, help_text='True 시 기존 동의자에게 재동의 요청 필요 여부 표시 (FE 인지용, 실제 플로우는 별도 구현)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '약관 버전',
                'verbose_name_plural': '약관 버전 목록',
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
    ]
