# Generated by Django 4.2.27 on 2026-06-19 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feature', '기능문의'), ('billing', '요금결제'), ('bug', '버그신고'), ('other', '기타')], max_length=30, verbose_name='문의 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[('open', '답변 대기'), ('answered', '답변 완료'), ('closed', '종료')], default='open', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성 설계사')),
            ],
            options={
                'verbose_name': '1:1 문의',
                'verbose_name_plural': '1:1 문의',
                'db_table': 'board_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='본문')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='관리자 숨김')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='소프트 삭제')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수(캐시)')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수(캐시)')),
                ('pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('category', models.CharField(blank=True, max_length=30, null=True, verbose_name='카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'board_post',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', '게시글'), ('comment', '댓글')], max_length=10, verbose_name='대상 유형')),
                ('object_id', models.BigIntegerField(verbose_name='대상 ID')),
                ('reason', models.CharField(choices=[('spam', '스팸/광고'), ('hate', '혐오/차별'), ('adult', '음란'), ('fake', '허위정보'), ('other', '기타')], max_length=30, verbose_name='신고 이유')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='상세 설명')),
                ('status', models.CharField(choices=[('pending', '처리 대기'), ('resolved', '처리 완료 (숨김)'), ('dismissed', '기각')], default='pending', max_length=10, verbose_name='처리 상태')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='처리 관리자')),
            ],
            options={
                'verbose_name': '신고',
                'verbose_name_plural': '신고',
                'db_table': 'board_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='boards.post', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='설계사')),
            ],
            options={
                'verbose_name': '게시글 좋아요',
                'verbose_name_plural': '게시글 좋아요',
                'db_table': 'board_post_like',
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500, verbose_name='파일 URL (S3/CDN)')),
                ('file_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME 타입')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='boards.post', verbose_name='게시글')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_attachments', to=settings.AUTH_USER_MODEL, verbose_name='업로드 설계사')),
            ],
            options={
                'verbose_name': '게시글 첨부',
                'verbose_name_plural': '게시글 첨부',
                'db_table': 'board_post_attachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='본문')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시됨')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='게시 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='관리자 작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'db_table': 'board_notice',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='답변 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_replies', to=settings.AUTH_USER_MODEL, verbose_name='답변 관리자')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.inquiry', verbose_name='문의')),
            ],
            options={
                'verbose_name': '문의 답변',
                'verbose_name_plural': '문의 답변',
                'db_table': 'board_inquiry_reply',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('question', models.CharField(max_length=300, verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시됨')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to=settings.AUTH_USER_MODEL, verbose_name='관리자 작성자')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'board_faq',
                'ordering': ['category', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='내용')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='관리자 숨김')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='소프트 삭제')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.comment', verbose_name='부모 댓글 (대댓글용)')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'board_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'content_type', 'object_id'), name='uniq_report_reporter_content'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_like_post_user'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='board_post_created_802429_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-created_at'], name='board_post_categor_217a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted', 'is_hidden', '-created_at'], name='board_post_is_dele_afb900_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='board_comme_post_id_676fe4_idx'),
        ),
    ]
