# Generated by Django 4.2.27 on 2026-07-12 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='슬러그')),
                ('body', models.TextField(verbose_name='본문(마크다운)')),
                ('excerpt', models.CharField(blank=True, default='', max_length=300, verbose_name='요약')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='커버 이미지')),
                ('category', models.CharField(choices=[('sales', '고객 늘리기'), ('coverage', '보장분석'), ('safety', '안심 가이드'), ('story', '설계사 이야기')], default='sales', max_length=30, verbose_name='카테고리')),
                ('tags', models.CharField(blank=True, default='', max_length=200, verbose_name='태그(쉼표 구분)')),
                ('is_published', models.BooleanField(default=False, verbose_name='게시됨')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='게시 시각')),
                ('seo_title', models.CharField(blank=True, default='', max_length=60, verbose_name='SEO 제목')),
                ('seo_description', models.CharField(blank=True, default='', max_length=160, verbose_name='SEO 설명')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='검색 제외(noindex)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '인파 노트 글',
                'verbose_name_plural': '인파 노트 글',
                'db_table': 'board_blog_post',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='board_blog__is_publ_9a1cde_idx'), models.Index(fields=['category', 'is_published'], name='board_blog__categor_12ab45_idx')],
            },
        ),
    ]
