# Generated by Django 4.2.27 on 2026-07-14 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='답변 이메일(익명)'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='meta',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='메타(화면 정보)'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='별점(1~5)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('feature', '기능문의'), ('billing', '요금결제'), ('bug', '버그신고'), ('other', '기타'), ('feedback', '이용 의견')], max_length=30, verbose_name='문의 유형'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성 설계사'),
        ),
    ]
