# Generated by Django 5.2.16 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_inquiry_contact_email_inquiry_meta_inquiry_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_asset_path',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='공개 정적 커버 경로'),
        ),
        migrations.CreateModel(
            name='BlogContentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=80, unique=True)),
                ('digest', models.CharField(max_length=64)),
                ('item_count', models.PositiveSmallIntegerField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board_blog_content_release',
                'ordering': ['-applied_at'],
            },
        ),
    ]
