# Generated by Django 5.2.16 on 2026-08-02 22:25

from django.db import migrations, models


LEGAL_REVIEW_SLUGS = (
    '보험-갈아타기-비교',
    '비교안내서-한눈에-보는-비교표',
    '보험-갈아타기-설계사-순서',
)


def lock_release_legal_posts(apps, schema_editor):
    BlogPost = apps.get_model('boards', 'BlogPost')
    BlogPost.objects.filter(slug__in=LEGAL_REVIEW_SLUGS).update(
        legal_review_required=True,
        review_gate='legal',
        is_published=False,
        published_at=None,
    )


def unlock_release_legal_posts(apps, schema_editor):
    BlogPost = apps.get_model('boards', 'BlogPost')
    BlogPost.objects.filter(slug__in=LEGAL_REVIEW_SLUGS).update(
        legal_review_required=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_blogpost_cover_asset_path_blogcontentrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontentrelease',
            name='before_snapshot',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogcontentrelease',
            name='after_snapshot',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='legal_review',
            field=models.JSONField(blank=True, null=True, verbose_name='법률 검토 기록'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='review_gate',
            field=models.CharField(choices=[('none', '추가 검토 없음'), ('legal', '법률 검토')], default='none', max_length=20, verbose_name='게시 전 검토'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='legal_review_required',
            field=models.BooleanField(default=False, editable=False, verbose_name='법률 검토 고정'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='legal_review_reviewer',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='법률 검토자'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='legal_review_credential',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='법률 검토 자격'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='legal_reviewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='법률 검토 시각'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='legal_review_reference',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='법률 검토 근거'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='legal_review_content_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='법률 검토 본문 해시'),
        ),
        migrations.RunPython(lock_release_legal_posts, unlock_release_legal_posts),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.CheckConstraint(
                condition=(models.Q(('is_published', False)) | (models.Q(('legal_review_required', False)) & ~models.Q(('review_gate', 'legal'))) | (~models.Q(('legal_review_reviewer', '')) & ~models.Q(('legal_review_credential', '')) & models.Q(('legal_reviewed_at__isnull', False)) & ~models.Q(('legal_review_reference', '')) & ~models.Q(('legal_review_content_digest', '')))),
                name='blog_legal_review_required_to_publish',
            ),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.CheckConstraint(
                condition=(models.Q(('legal_review_required', False)) | models.Q(('review_gate', 'legal'))),
                name='blog_required_review_gate_locked',
            ),
        ),
    ]
