# Generated by Django 4.2.27 on 2026-06-19 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('expiry_soon', '만기 임박'), ('birthday_soon', '고객 생일'), ('consult_reminder', '상담 약속'), ('task_due', '할 일 마감'), ('share_unread', '미열람 공유')], max_length=30, verbose_name='알림 유형')),
                ('days_before', models.PositiveSmallIntegerField(default=1, help_text='0~90. share_unread는 0 고정(24h = 0일 전 특별 해석).', verbose_name='발화 기준(며칠 전)')),
                ('enabled', models.BooleanField(default=True, verbose_name='이 유형 알림 활성')),
                ('email_enabled', models.BooleanField(default=False, help_text='opt-in. 기본 꺼짐. 켜면 발화 시 설계사 본인 가입 이메일로 발송.', verbose_name='이메일 알림 활성')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
                'db_table': 'reminder_rule',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('expiry_soon', '만기 임박'), ('birthday_soon', '고객 생일'), ('consult_reminder', '상담 약속'), ('task_due', '할 일 마감'), ('share_unread', '미열람 공유')], max_length=30, verbose_name='알림 유형')),
                ('title', models.CharField(max_length=200, verbose_name='알림 제목')),
                ('body', models.TextField(verbose_name='알림 본문')),
                ('target_date', models.DateField(blank=True, help_text='만기일/생일/약속일/마감일 — 정렬·그룹화 기준 (dev/22 §4.2)', null=True, verbose_name='트리거 기준일')),
                ('calendar_event_id', models.PositiveIntegerField(blank=True, help_text='CalendarEvent(미생성 앱) PK. 앱 생성 후 ForeignKey로 교체.', null=True, verbose_name='연관 캘린더 이벤트 ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('sent_email', models.BooleanField(default=False, help_text='opt-in 설정 기반. 인프라 미결 시 미전환(dev/22 §8 G-2).', verbose_name='이메일 발송 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='customers.customer', verbose_name='연관 고객')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reminderrule',
            constraint=models.UniqueConstraint(fields=('owner', 'rule_type'), name='uniq_reminder_rule_owner_type'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['owner', '-created_at'], name='notificatio_owner_i_2e6490_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['owner', 'is_read'], name='notificatio_owner_i_7126aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False), ('target_date__isnull', False)), fields=('owner', 'notif_type', 'target_date', 'customer'), name='uniq_notif_owner_type_date_customer'),
        ),
    ]
