# Generated by Django 4.2.27 on 2026-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_lead_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('expiry_soon', '만기 임박'), ('birthday_soon', '고객 생일'), ('consult_reminder', '상담 약속'), ('task_due', '할 일 마감'), ('share_unread', '미열람 공유'), ('unpaid_d_alert', '미납 임박'), ('self_diagnosis_lead', '셀프진단 리드'), ('board_comment', '게시글 댓글'), ('board_like', '게시글 좋아요'), ('meeting_booked', '미팅 예약됨')], max_length=30, verbose_name='알림 유형'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='rule_type',
            field=models.CharField(choices=[('expiry_soon', '만기 임박'), ('birthday_soon', '고객 생일'), ('consult_reminder', '상담 약속'), ('task_due', '할 일 마감'), ('share_unread', '미열람 공유'), ('unpaid_d_alert', '미납 임박'), ('self_diagnosis_lead', '셀프진단 리드'), ('board_comment', '게시글 댓글'), ('board_like', '게시글 좋아요'), ('meeting_booked', '미팅 예약됨')], max_length=30, verbose_name='알림 유형'),
        ),
    ]
