# Generated by Django 4.2.27 on 2026-06-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_meeting_status_workhour'),
        ('notifications', '0006_alter_notification_notif_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='booking.meeting', verbose_name='연관 미팅'),
        ),
    ]
