# Generated by Django 4.2.27 on 2026-07-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_notif_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('expiry_soon', '만기 임박'), ('birthday_soon', '고객 생일'), ('consult_reminder', '상담 약속'), ('task_due', '할 일 마감'), ('share_unread', '미열람 공유'), ('unpaid_d_alert', '미납 임박'), ('self_diagnosis_lead', '셀프진단 리드'), ('board_comment', '게시글 댓글'), ('board_like', '게시글 좋아요'), ('meeting_booked', '미팅 예약됨'), ('promotion_status', '판촉물 상태'), ('promotion_digital_requested', '전자자료 요청'), ('promotion_digital_ready', '전자자료 준비됨'), ('coverage_flag_requested', '담보 위치 확인 요청'), ('signup_verify_flatline', '이메일 인증 멈춤'), ('inquiry_answered', '문의 답변 도착'), ('inquiry_received', '새 문의 접수')], max_length=30, verbose_name='알림 유형'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='rule_type',
            field=models.CharField(choices=[('expiry_soon', '만기 임박'), ('birthday_soon', '고객 생일'), ('consult_reminder', '상담 약속'), ('task_due', '할 일 마감'), ('share_unread', '미열람 공유'), ('unpaid_d_alert', '미납 임박'), ('self_diagnosis_lead', '셀프진단 리드'), ('board_comment', '게시글 댓글'), ('board_like', '게시글 좋아요'), ('meeting_booked', '미팅 예약됨'), ('promotion_status', '판촉물 상태'), ('promotion_digital_requested', '전자자료 요청'), ('promotion_digital_ready', '전자자료 준비됨'), ('coverage_flag_requested', '담보 위치 확인 요청'), ('signup_verify_flatline', '이메일 인증 멈춤'), ('inquiry_answered', '문의 답변 도착'), ('inquiry_received', '새 문의 접수')], max_length=30, verbose_name='알림 유형'),
        ),
    ]
