# Generated by Django 4.2.27 on 2026-07-17

from django.db import migrations, models


NOTIFICATION_CHOICES = [
    ('expiry_soon', '만기 임박'),
    ('birthday_soon', '고객 생일'),
    ('consult_reminder', '상담 약속'),
    ('task_due', '할 일 마감'),
    ('share_unread', '미열람 공유'),
    ('unpaid_d_alert', '미납 임박'),
    ('self_diagnosis_lead', '셀프진단 리드'),
    ('board_comment', '게시글 댓글'),
    ('board_like', '게시글 좋아요'),
    ('meeting_booked', '미팅 예약됨'),
    ('promotion_status', '판촉물 상태'),
    ('promotion_digital_requested', '전자자료 요청'),
    ('promotion_digital_ready', '전자자료 준비됨'),
    ('coverage_flag_requested', '담보 위치 확인 요청'),
    ('signup_verify_flatline', '이메일 인증 멈춤'),
    ('inquiry_answered', '문의 답변 도착'),
    ('inquiry_received', '새 문의 접수'),
    ('recruiting_application', '새 영입 지원'),
    ('recruiting_followup', '영입 다음 연락'),
    ('recruiting_settlement', '정착 확인'),
    ('manager_promoted', '관리자 기능 활성화'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notification_notif_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(
                blank=True,
                help_text='내부 알림 생산용 키. 기존 알림은 NULL로 유지.',
                max_length=120,
                null=True,
                unique=True,
                verbose_name='중복 방지 키',
            ),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(
                choices=NOTIFICATION_CHOICES,
                max_length=30,
                verbose_name='알림 유형',
            ),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='rule_type',
            field=models.CharField(
                choices=NOTIFICATION_CHOICES,
                max_length=30,
                verbose_name='알림 유형',
            ),
        ),
    ]
