# Generated by Django 4.2.27 on 2026-06-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inpa.accounts.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입 시각')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', inpa.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_password_changed', models.DateTimeField(blank=True, null=True)),
                ('tos_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('tos_doc_version', models.CharField(default='', max_length=30)),
                ('pp_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('pp_doc_version', models.CharField(default='', max_length=30)),
                ('marketing_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_type', models.SmallIntegerField(blank=True, choices=[(1, '생명'), (2, '손해'), (3, '교차')], null=True)),
                ('license_self_declared', models.BooleanField(default=False)),
                ('license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('career_years', models.IntegerField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_dormant', models.BooleanField(default=False)),
                ('dormant_at', models.DateTimeField(blank=True, null=True)),
                ('dormancy_warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('will_delete_at', models.DateTimeField(blank=True, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_profile',
            },
        ),
    ]
