# Generated by Django 4.2.27 on 2026-06-20 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliation_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '전속'), (2, 'GA')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cohort_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
