# Generated by Django 4.2.27 on 2026-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_day1_hooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager_share_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
