# Generated by Django 4.2.27 on 2026-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phase2_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booking_default_duration',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='기본 미팅 시간(분)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='booking_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='대면 기본 장소'),
        ),
        migrations.AddField(
            model_name='profile',
            name='booking_msg_template',
            field=models.TextField(blank=True, default='', verbose_name='미팅 예약 메시지 템플릿'),
        ),
    ]
