# Generated by Django 4.2.27 on 2026-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_booking_default_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='설계사 이름'),
        ),
    ]
