# Generated by Django 4.2.27 on 2026-06-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_calendar_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='구글 캘린더 연동 시각'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_calendar_mask_name',
            field=models.BooleanField(default=True, verbose_name='캘린더 이벤트 이름 마스킹'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_calendar_refresh_token',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='구글 캘린더 refresh token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='구글 sub'),
        ),
    ]
