# Generated by Django 4.2.27 on 2026-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_google_calendar_connected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booking_buffer_min',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='미팅 앞뒤 여유(분)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='직책'),
        ),
    ]
