# Generated by Django 4.2.27 on 2026-06-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_booking_buffer_min_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager_share_level',
            field=models.CharField(choices=[('none', '공유 안 함'), ('activity', '활동만'), ('full', '활동+실적')], default='none', max_length=10),
        ),
    ]
