# Generated by Django 4.2.27 on 2026-06-30 04:40
# 레거시 manager_share_opt_in(bool) → manager_share_level(단계) 백필.
#   True → 'full'(활동+실적), False → 'none'(공유 안 함). 기존 동의자는 전부 공유 유지.

from django.db import migrations


def forwards(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.filter(manager_share_opt_in=True).update(manager_share_level='full')
    Profile.objects.filter(manager_share_opt_in=False).update(manager_share_level='none')


def backwards(apps, schema_editor):
    # level → opt_in 역동기화(없으면 무손실 역행).
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.exclude(manager_share_level='none').update(manager_share_opt_in=True)
    Profile.objects.filter(manager_share_level='none').update(manager_share_opt_in=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_manager_share_level'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
