# Generated by Django 4.2.27 on 2026-06-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_manager_share_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro_text',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='한줄소개'),
        ),
    ]
