# Generated by Django 4.2.27 on 2026-07-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='전화번호'),
        ),
    ]
