# Generated by Django 4.2.27 on 2026-07-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='유입 캠페인'),
        ),
        migrations.AddField(
            model_name='profile',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='유입 매체'),
        ),
        migrations.AddField(
            model_name='profile',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='유입 소스'),
        ),
    ]
