# Generated by Django 5.2.16 on 2026-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_manager_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tour_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
