# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_tour_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_showcase',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
