# Generated by Django 4.2.27 on 2026-06-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('free', 'Free'), ('plus', 'Plus')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50, verbose_name='표시 이름')),
                ('price_krw', models.PositiveIntegerField(default=0, verbose_name='월 요금(원)')),
                ('description', models.TextField(blank=True, verbose_name='설명(관리자 메모)')),
                ('limit_ocr', models.PositiveIntegerField(blank=True, default=10, help_text='null=무제한. Free 기본 10건.', null=True, verbose_name='OCR 한도(월)')),
                ('limit_ai_compare', models.PositiveIntegerField(blank=True, default=5, help_text='null=무제한. Free 기본 5건.', null=True, verbose_name='AI비교안내서 한도(월)')),
                ('limit_analysis', models.PositiveIntegerField(blank=True, default=10, help_text='null=무제한. Free 기본 10건.', null=True, verbose_name='AI분석 한도(월)')),
                ('limit_promotion', models.PositiveIntegerField(blank=True, default=5, help_text='null=무제한. Free 기본 5건.', null=True, verbose_name='판촉물 한도(월)')),
                ('is_active', models.BooleanField(default=True, help_text='False 시 신규 Subscription 생성 불가.', verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '요금제',
                'verbose_name_plural': '요금제',
                'db_table': 'billing_plan',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '활성'), ('cancelled', '해지'), ('expired', '만료'), ('trial', '체험')], default='active', max_length=20, verbose_name='상태')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('expires_at', models.DateTimeField(blank=True, help_text='null = 무기한(Free).', null=True, verbose_name='만료 시각')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='해지 시각')),
                ('pg_subscription_id', models.CharField(blank=True, default='', help_text='Phase 2 PG 자동 결제 연동 시 채움.', max_length=100, verbose_name='PG 구독 ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan', verbose_name='요금제')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='설계사')),
            ],
            options={
                'verbose_name': '구독',
                'verbose_name_plural': '구독',
                'db_table': 'billing_subscription',
            },
        ),
        migrations.CreateModel(
            name='UsageMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ocr', 'OCR 증권 분석'), ('ai_compare', 'AI 비교안내서'), ('analysis', 'AI 분析·메시지'), ('promotion', '판촉물 주문')], max_length=30, verbose_name='액션')),
                ('year_month', models.CharField(help_text='예: "2026-06". lazy reset 기준.', max_length=7, verbose_name='연월(YYYY-MM)')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='사용 횟수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_meters', to=settings.AUTH_USER_MODEL, verbose_name='설계사')),
            ],
            options={
                'verbose_name': '사용량 미터',
                'verbose_name_plural': '사용량 미터',
                'db_table': 'billing_usage_meter',
                'indexes': [models.Index(fields=['user', 'year_month'], name='billing_usa_user_id_5192b2_idx')],
                'unique_together': {('user', 'action', 'year_month')},
            },
        ),
    ]
