# Generated by Django 4.2.27 on 2026-06-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30, verbose_name='호출 목적')),
                ('model', models.CharField(max_length=60, verbose_name='Claude 모델')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='입력 토큰')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='출력 토큰')),
                ('cache_read_input_tokens', models.PositiveIntegerField(default=0, help_text='prompt caching 재사용(~0.1x 비용).', verbose_name='캐시 읽기 토큰')),
                ('cache_creation_input_tokens', models.PositiveIntegerField(default=0, help_text='prompt caching 신규 작성(~1.25x 비용).', verbose_name='캐시 작성 토큰')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Claude API 로그',
                'verbose_name_plural': 'Claude API 로그',
                'db_table': 'billing_claude_api_log',
                'indexes': [models.Index(fields=['action', 'created_at'], name='billing_cla_action_2b9d85_idx'), models.Index(fields=['model', 'created_at'], name='billing_cla_model_a911ea_idx')],
            },
        ),
    ]
