# Generated by Django 4.2.27 on 2026-07-01 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_claudeapilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='대문자·숫자. 비워두면 자동 생성(INPA-XXXXXXXX).', max_length=32, unique=True, verbose_name='쿠폰 코드')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='기본 30일(1개월).', verbose_name='부여 기간(일)')),
                ('max_redemptions', models.PositiveIntegerField(default=1, help_text='이 코드를 총 몇 명이 쓸 수 있는지. 기본 1(1회용).', verbose_name='최대 사용 횟수')),
                ('redeemed_count', models.PositiveIntegerField(default=0, verbose_name='사용된 횟수')),
                ('expires_at', models.DateTimeField(blank=True, help_text='이 시각 이후 사용 불가. null=무기한.', null=True, verbose_name='코드 유효기한')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='메모(관리자)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(help_text='보통 Plus.', on_delete=django.db.models.deletion.PROTECT, to='billing.plan', verbose_name='부여 요금제')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰',
                'db_table': 'billing_coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_until', models.DateTimeField(verbose_name='부여 만료 시각')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.coupon', verbose_name='쿠폰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='설계사')),
            ],
            options={
                'verbose_name': '쿠폰 사용',
                'verbose_name_plural': '쿠폰 사용',
                'db_table': 'billing_coupon_redemption',
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
