# Generated by Django 4.2.27 on 2026-07-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_coupon_couponredemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_tier_unlimited', models.BooleanField(default=True, help_text='True=모든 한도 무시(베타 무차감). False=유료 한도 적용(402 발동).', verbose_name='무료 무제한(베타)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '런타임 설정',
                'verbose_name_plural': '런타임 설정',
                'db_table': 'billing_runtime_config',
            },
        ),
    ]
