# Generated by Django 4.2.27 on 2026-07-07 06:58
# Plan.code choices에 'manager' 추가 (DB 무영향)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plus_price_and_super_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('manager', 'Manager'), ('super', 'Super')], max_length=20, unique=True),
        ),
    ]
