# Generated by Django 4.2.27 on 2026-07-09 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_manager_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudeapilog',
            name='carrier_code',
            field=models.SmallIntegerField(blank=True, help_text='손해=raw index / 생명=200+index (UnmatchedLog 규약과 동일). 미상=null.', null=True, verbose_name='보험사 코드'),
        ),
        migrations.AddField(
            model_name='claudeapilog',
            name='cost_krw',
            field=models.DecimalField(decimal_places=2, default=0, help_text='★ 추정치 — 토큰×단가×환율 파생값. 정밀 청구서 아님(§6 정직성).', max_digits=10, verbose_name='추정 비용(원)'),
        ),
        migrations.AddField(
            model_name='claudeapilog',
            name='matched_count',
            field=models.SmallIntegerField(default=0, verbose_name='매칭 담보 수'),
        ),
        migrations.AddField(
            model_name='claudeapilog',
            name='parse_outcome',
            field=models.CharField(choices=[('success', '성공'), ('empty', '결과 없음'), ('json_invalid', 'JSON 형식 오류'), ('api_error', 'API 오류'), ('timeout', '시간 초과'), ('no_key', '키 미설정'), ('package_missing', '패키지 없음')], db_index=True, default='success', max_length=20, verbose_name='파싱 결과'),
        ),
        migrations.AddField(
            model_name='claudeapilog',
            name='unmatched_count',
            field=models.SmallIntegerField(default=0, verbose_name='미매칭 담보 수'),
        ),
        migrations.AddField(
            model_name='claudeapilog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='공개 경로(/d 셀프진단)는 null.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claude_api_logs', to=settings.AUTH_USER_MODEL, verbose_name='호출 설계사'),
        ),
        migrations.AddIndex(
            model_name='claudeapilog',
            index=models.Index(fields=['created_at'], name='billing_cla_created_abd879_idx'),
        ),
        migrations.AddIndex(
            model_name='claudeapilog',
            index=models.Index(fields=['parse_outcome'], name='billing_cla_parse_o_61099a_idx'),
        ),
    ]
