# Generated by Django 4.2.27 on 2026-07-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_claudeapilog_cost_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='can_use_team',
            field=models.BooleanField(default=False, help_text='True면 /manager 대시보드·팀 초대 링크를 사용할 수 있어요. settings.MANAGER_PLAN_GATE_ENABLED=True일 때만 실제로 게이트가 적용됩니다(기본 False=미적용).', verbose_name='팀 관리 기능 사용 가능'),
        ),
    ]
