# Generated by Django 4.2.27 on 2026-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_plan_can_use_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limit_customer',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='null=무제한. Free 기본 5명(월). 설계사가 능동으로 추가하는 고객만 집계(셀프진단·소개 카드 인바운드 리드는 미집계).', null=True, verbose_name='신규 고객 추가 한도(월)'),
        ),
        migrations.AlterField(
            model_name='usagemeter',
            name='action',
            field=models.CharField(choices=[('ocr', 'OCR 증권 분석'), ('ai_compare', 'AI 비교안내서'), ('analysis', 'AI 분析·메시지'), ('promotion', '판촉물 주문'), ('customer', '고객 추가')], max_length=30, verbose_name='액션'),
        ),
    ]
