# Generated by Django 4.2.27 on 2026-07-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_plan_limit_customer_alter_usagemeter_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_annual_krw',
            field=models.PositiveIntegerField(blank=True, help_text='연 요금(부가세 별도). 미설정 시 월가×10 폴백(연구독=12개월을 10개월가로).', null=True, verbose_name='연 요금(원)'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='first_paid_bonus_enabled',
            field=models.BooleanField(default=False, help_text='True=첫 유료 구독 부여 시 +1개월 보너스(사용자당 1회). 기본 OFF.', verbose_name='첫 유료 결제 보너스 이벤트'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Phase B 정기결제 토대. True면 next_billing_at 도래 시 빌링키로 자동 청구(로직 후속).', verbose_name='자동 갱신'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', '월간'), ('annual', '연간')], default='monthly', help_text='monthly=월간 / annual=연간(12개월을 10개월가로).', max_length=10, verbose_name='결제 주기'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='first_paid_bonus_used',
            field=models.BooleanField(default=False, help_text='첫 유료 구독 1회에 한해 +1개월 이벤트 보너스가 적용됐는지(사용자당 1회 보장).', verbose_name='첫 유료 보너스 소진'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billing_at',
            field=models.DateTimeField(blank=True, help_text='Phase B 정기결제 토대. auto_renew 청구 잡의 기준 시각(로직 후속).', null=True, verbose_name='다음 결제 예정 시각'),
        ),
    ]
