# Generated by Django 5.2.16 on 2026-07-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_plus_team_capability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='limit_ai_compare',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='null=무제한. Free 기본 5건.', null=True, verbose_name='증권 비교 한도(월)'),
        ),
        migrations.AlterField(
            model_name='usagemeter',
            name='action',
            field=models.CharField(choices=[('ocr', 'OCR 증권 분석'), ('ai_compare', '증권 비교'), ('analysis', 'AI 분析·메시지'), ('promotion', '판촉물 주문'), ('customer', '고객 추가')], max_length=30, verbose_name='액션'),
        ),
    ]
