# Generated by Django 5.2.16 on 2026-07-26 12:32

from django.db import migrations, models


def backfill_consultation_limits(apps, schema_editor):
    Plan = apps.get_model('billing', 'Plan')
    limits = {
        'free': (5, 150),
        'plus': (30, 900),
        'manager': (30, 900),
        'super': (100, 3000),
    }
    for code, (summary_limit, minute_limit) in limits.items():
        Plan.objects.filter(code=code).update(
            limit_consultation_summary=summary_limit,
            limit_consultation_minute=minute_limit,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_neutral_comparison_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limit_consultation_minute',
            field=models.PositiveIntegerField(blank=True, default=150, help_text='외부 음성 처리가 시작된 올림 분수. null=무제한.', null=True, verbose_name='상담 음성 처리 분(월)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='limit_consultation_summary',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='녹음 파일별 최초 AI 요약 성공 건수. null=무제한.', null=True, verbose_name='상담 요약 한도(월)'),
        ),
        migrations.RunPython(
            backfill_consultation_limits,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='usagemeter',
            name='action',
            field=models.CharField(choices=[('ocr', 'OCR 증권 분석'), ('ai_compare', '증권 비교'), ('analysis', 'AI 분析·메시지'), ('promotion', '판촉물 주문'), ('customer', '고객 추가'), ('consultation_summary', '상담 요약'), ('consultation_minute', '상담 음성 처리 분')], max_length=30, verbose_name='액션'),
        ),
    ]
