# Generated by Django 5.2.16 on 2026-07-26 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_plan_limit_consultation_minute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=120, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'received'), ('verified', 'verified'), ('processed', 'processed'), ('rejected', 'rejected')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_webhook_inbox',
            },
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='billing_card_registration_enabled',
            field=models.BooleanField(default=False, help_text='환경 게이트와 함께 열려야 카드 등록을 시작합니다.', verbose_name='카드 등록형 쿠폰'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='billing_reconciliation_enabled',
            field=models.BooleanField(default=False, help_text='미확정 거래 조회와 늦은 승인 취소를 운영합니다.', verbose_name='결제 대사'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='billing_recurring_charge_enabled',
            field=models.BooleanField(default=False, help_text='대사 기능과 베타 한도 종료까지 충족해야 승인합니다.', verbose_name='월 정기 승인'),
        ),
        migrations.CreateModel(
            name='BillingAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'trialing'), ('renewal_processing', 'renewal_processing'), ('active', 'active'), ('past_due_unknown', 'past_due_unknown'), ('canceled', 'canceled'), ('free', 'free')], default='trialing', max_length=24)),
                ('billing_anchor_day', models.PositiveSmallIntegerField()),
                ('trial_duration_months', models.PositiveSmallIntegerField(default=1)),
                ('cycle_sequence', models.PositiveIntegerField(default=0)),
                ('current_period_starts_on', models.DateField()),
                ('current_period_ends_on', models.DateField()),
                ('next_charge_date', models.DateField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_agreements', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_agreement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_agreement',
            },
        ),
        migrations.CreateModel(
            name='BillingNoticeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120)),
                ('notice_type', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=40)),
                ('lease_device_hash', models.CharField(blank=True, default='', max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('rendered_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_notice_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_notice_event',
            },
        ),
        migrations.CreateModel(
            name='CouponClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('held', 'held'), ('redeemed', 'redeemed'), ('released', 'released'), ('expired', 'expired')], default='held', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='billing.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_coupon_claim',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.TextField()),
                ('key_version', models.CharField(max_length=20)),
                ('card_brand', models.CharField(blank=True, default='', max_length=40)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('status', models.CharField(choices=[('active', 'active'), ('revocation_pending', 'revocation_pending'), ('revoked', 'revoked')], default='active', max_length=24)),
                ('revocation_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=40)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tokens', to='billing.billingagreement')),
            ],
            options={
                'db_table': 'billing_payment_method_token',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_sequence', models.PositiveIntegerField()),
                ('merchant_order_id', models.CharField(max_length=80, unique=True)),
                ('amount_krw', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('created', 'created'), ('submitted', 'submitted'), ('approved', 'approved'), ('declined', 'declined'), ('unknown', 'unknown'), ('canceled', 'canceled'), ('refunded', 'refunded')], default='created', max_length=20)),
                ('failure_code', models.CharField(blank=True, default='', max_length=40)),
                ('unknown_since', models.DateTimeField(blank=True, null=True)),
                ('temporary_access_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='billing.billingagreement')),
            ],
            options={
                'db_table': 'billing_payment_order',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('provider_request_id', models.CharField(max_length=80, unique=True)),
                ('result_kind', models.CharField(blank=True, choices=[('approved', 'approved'), ('declined', 'declined'), ('unknown', 'unknown')], default='', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('provider_code', models.CharField(blank=True, default='', max_length=40)),
                ('response_hash', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='billing.paymentorder')),
            ],
            options={
                'db_table': 'billing_payment_attempt',
            },
        ),
        migrations.CreateModel(
            name='RecurringPaymentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trial_start', 'trial_start'), ('first_charge', 'first_charge')], max_length=20)),
                ('consent_version', models.CharField(max_length=40)),
                ('plan_code', models.CharField(max_length=20)),
                ('amount_krw', models.PositiveIntegerField()),
                ('charge_date', models.DateField()),
                ('card_label', models.CharField(blank=True, default='', max_length=80)),
                ('cancel_path', models.CharField(default='/settings/billing', max_length=100)),
                ('cancel_effect', models.DateField()),
                ('display_snapshot_hash', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField()),
                ('network_hmac', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_consents', to='billing.billingagreement')),
            ],
            options={
                'db_table': 'billing_recurring_payment_consent',
            },
        ),
        migrations.AddConstraint(
            model_name='billingagreement',
            constraint=models.CheckConstraint(condition=models.Q(('billing_anchor_day__gte', 1), ('billing_anchor_day__lte', 31)), name='billing_anchor_day_1_31'),
        ),
        migrations.AddConstraint(
            model_name='billingagreement',
            constraint=models.CheckConstraint(condition=models.Q(('trial_duration_months__gte', 1), ('trial_duration_months__lte', 3)), name='billing_trial_months_1_3'),
        ),
        migrations.AddConstraint(
            model_name='billingnoticeevent',
            constraint=models.UniqueConstraint(fields=('user', 'event_key', 'notice_type'), name='uniq_billing_notice_event'),
        ),
        migrations.AddConstraint(
            model_name='couponclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('held', 'redeemed'))), fields=('coupon', 'user'), name='uniq_billing_live_coupon_claim'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethodtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('agreement',), name='uniq_billing_active_token'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'due_date'], name='billing_pay_status_03e412_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.UniqueConstraint(fields=('agreement', 'cycle_sequence'), name='uniq_billing_agreement_cycle'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('order', 'attempt_no'), name='uniq_billing_order_attempt'),
        ),
        migrations.AddConstraint(
            model_name='recurringpaymentconsent',
            constraint=models.UniqueConstraint(fields=('agreement', 'kind', 'charge_date', 'display_snapshot_hash'), name='uniq_billing_consent_snapshot'),
        ),
    ]
