# Generated by Django 5.2.16 on 2026-07-26 15:15

from django.db import migrations, models


def copy_legacy_redeem_deadline(apps, schema_editor):
    Coupon = apps.get_model('billing', 'Coupon')
    Coupon.objects.filter(
        redeem_by__isnull=True,
        expires_at__isnull=False,
    ).update(redeem_by=models.F('expires_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_webhookinbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_kind',
            field=models.CharField(choices=[('legacy_grant', '기존 일수형'), ('recurring_trial', '카드 등록형 무료 이용')], default='legacy_grant', max_length=24, verbose_name='쿠폰 종류'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='카드 등록형 쿠폰은 1~3개월만 선택합니다.', null=True, verbose_name='무료 이용 개월'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='redeem_by',
            field=models.DateTimeField(blank=True, help_text='카드 등록형 쿠폰은 이 시각까지 시작할 수 있습니다.', null=True, verbose_name='쿠폰 사용 기한'),
        ),
        migrations.RunPython(
            copy_legacy_redeem_deadline,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coupon_kind', 'legacy_grant'), ('duration_days__gte', 1), ('duration_months__isnull', True)), models.Q(('coupon_kind', 'recurring_trial'), ('duration_months__gte', 1), ('duration_months__lte', 3), ('redeem_by__isnull', False)), _connector='OR'), name='billing_coupon_kind_duration_valid'),
        ),
    ]
