# Generated by Django 5.2.16 on 2026-07-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_coupon_coupon_kind_coupon_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingagreement',
            name='coupon_claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='billing.couponclaim'),
        ),
    ]
