# Generated by Django 5.2.16 on 2026-07-26 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_billingagreement_coupon_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.CharField(blank=True, default='', max_length=80)),
                ('request_key', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_admin_action',
                'indexes': [models.Index(fields=['action', '-created_at'], name='billing_adm_action_65c4f6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('request_key', ''), _negated=True), fields=('request_key',), name='uniq_billing_admin_request_key')],
            },
        ),
    ]
