# Generated by Django 5.2.16 on 2026-07-27 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_billingadminaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitGrantLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_hmac', models.CharField(max_length=64)),
                ('key_version', models.CharField(max_length=20)),
                ('benefit_code', models.CharField(default='plus_trial_month', max_length=40)),
                ('granted_at', models.DateTimeField()),
                ('granted_until', models.DateTimeField()),
                ('coupon_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_grant_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_benefit_grant_ledger',
            },
        ),
        migrations.CreateModel(
            name='ManualBenefitReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_hmac', models.CharField(max_length=64)),
                ('key_version', models.CharField(max_length=20)),
                ('phone_last4', models.CharField(max_length=4)),
                ('benefit_code', models.CharField(default='plus_trial_month', max_length=40)),
                ('contact_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', '접수'), ('approved', '승인'), ('rejected', '반려'), ('consumed', '지급 완료')], default='pending', max_length=20)),
                ('decision_reason', models.CharField(blank=True, default='', max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_benefit_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_benefit_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_manual_benefit_review',
            },
        ),
        migrations.CreateModel(
            name='BenefitGrantException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_hmac', models.CharField(max_length=64)),
                ('key_version', models.CharField(max_length=20)),
                ('benefit_code', models.CharField(max_length=40)),
                ('granted_at', models.DateTimeField()),
                ('granted_until', models.DateTimeField()),
                ('coupon_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_grant_exceptions', to=settings.AUTH_USER_MODEL)),
                ('original_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_exceptions', to='billing.benefitgrantledger')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grant_exception', to='billing.manualbenefitreview')),
            ],
            options={
                'db_table': 'billing_benefit_grant_exception',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_hmac', models.CharField(max_length=64)),
                ('key_version', models.CharField(max_length=20)),
                ('phone_last4', models.CharField(max_length=4)),
                ('otp_hash', models.CharField(max_length=256)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_transaction_ref', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_phone_verification_challenge',
            },
        ),
        migrations.CreateModel(
            name='VerifiedPhoneIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hmac', models.CharField(max_length=64)),
                ('key_version', models.CharField(max_length=20)),
                ('phone_last4', models.CharField(max_length=4)),
                ('provider', models.CharField(default='solapi_sms', max_length=30)),
                ('verified_at', models.DateTimeField()),
                ('provider_transaction_ref', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_phone_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_verified_phone_identity',
            },
        ),
        migrations.AddIndex(
            model_name='benefitgrantledger',
            index=models.Index(fields=['benefit_code', '-granted_at'], name='billing_ben_benefit_73f148_idx'),
        ),
        migrations.AddConstraint(
            model_name='benefitgrantledger',
            constraint=models.UniqueConstraint(fields=('identity_hmac', 'benefit_code'), name='uniq_billing_phone_benefit'),
        ),
        migrations.AddIndex(
            model_name='manualbenefitreview',
            index=models.Index(fields=['status', '-created_at'], name='billing_man_status_1ce9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbenefitreview',
            index=models.Index(fields=['identity_hmac', 'benefit_code'], name='billing_man_identit_38f329_idx'),
        ),
        migrations.AddConstraint(
            model_name='manualbenefitreview',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('user', 'identity_hmac', 'benefit_code'), name='uniq_billing_active_benefit_review'),
        ),
        migrations.AddIndex(
            model_name='benefitgrantexception',
            index=models.Index(fields=['benefit_code', '-granted_at'], name='billing_ben_benefit_e6eb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['user', '-created_at'], name='billing_pho_user_id_f5c1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['phone_hmac', '-created_at'], name='billing_pho_phone_h_14b436_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['expires_at'], name='billing_pho_expires_0c3df7_idx'),
        ),
        migrations.AddConstraint(
            model_name='phoneverificationchallenge',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='billing_phone_challenge_max_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='phoneverificationchallenge',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='billing_phone_challenge_attempts_within_limit'),
        ),
        migrations.AddIndex(
            model_name='verifiedphoneidentity',
            index=models.Index(fields=['phone_hmac', 'key_version'], name='billing_ver_phone_h_54492f_idx'),
        ),
    ]
