# Generated by Django 4.2.27 on 2026-06-21 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_consentlog_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='시작 시각')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='소요(분)')),
                ('status', models.CharField(choices=[('open', '열림'), ('booked', '예약됨'), ('canceled', '취소됨')], default='open', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_slots', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
            ],
            options={
                'verbose_name': '미팅 슬롯',
                'verbose_name_plural': '미팅 슬롯',
                'db_table': 'meeting_slot',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='시작 시각')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='소요(분)')),
                ('method', models.CharField(choices=[('in_person', '대면'), ('phone', '전화'), ('video', '화상')], max_length=10, verbose_name='방식')),
                ('location_detail', models.CharField(blank=True, default='', max_length=200, verbose_name='장소')),
                ('customer_note', models.TextField(blank=True, default='', verbose_name='고객 메모')),
                ('status', models.CharField(choices=[('confirmed', '확정'), ('canceled', '취소됨')], default='confirmed', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='customers.customer', verbose_name='고객')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='booking.meetingslot')),
            ],
            options={
                'verbose_name': '미팅',
                'verbose_name_plural': '미팅',
                'db_table': 'meeting',
                'ordering': ['start_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meetingslot',
            index=models.Index(fields=['owner', 'status', 'start_at'], name='meeting_slo_owner_i_815169_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingslot',
            constraint=models.UniqueConstraint(fields=('owner', 'start_at'), name='uniq_slot_owner_start'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['owner', 'status', 'start_at'], name='meeting_owner_i_921b38_idx'),
        ),
    ]
