# Generated by Django 4.2.27 on 2026-06-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='google_event_id',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='구글 캘린더 이벤트 ID'),
        ),
    ]
