# Generated by Django 4.2.27 on 2026-06-28 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_meeting_google_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('confirmed', '확정'), ('canceled', '취소됨'), ('declined', '거절됨')], default='confirmed', max_length=10, verbose_name='상태'),
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='요일(0=월..6=일)')),
                ('start_time', models.TimeField(verbose_name='시작')),
                ('end_time', models.TimeField(verbose_name='종료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
            ],
            options={
                'verbose_name': '업무시간',
                'verbose_name_plural': '업무시간',
                'db_table': 'work_hour',
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['owner', 'weekday'], name='work_hour_owner_i_b9b315_idx')],
            },
        ),
    ]
