# Generated by Django 5.2.16 on 2026-08-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_meeting_status_workhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='calendar_cleanup_pending',
            field=models.BooleanField(default=False, verbose_name='캘린더 정리 대기'),
        ),
    ]
