# Generated by Django 4.2.27 on 2026-06-19 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('overseas_medical', '병력 국외이전 (Claude API, 미국)'), ('medical_sensitive', '민감정보(병력) 처리'), ('marketing', '마케팅 수신')], max_length=50, verbose_name='동의 범위')),
                ('purpose', models.CharField(blank=True, default='', max_length=200, verbose_name='처리 목적')),
                ('doc_version', models.CharField(blank=True, default='', max_length=30, verbose_name='약관 버전')),
                ('agreed_at', models.DateTimeField(auto_now_add=True, verbose_name='동의 시각')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='동의 IP')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='철회 시각')),
                ('revoke_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='철회 IP')),
            ],
            options={
                'verbose_name': '동의 로그',
                'verbose_name_plural': '동의 로그',
                'db_table': 'consent_log',
                'ordering': ['-agreed_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('mobile_phone_number', models.CharField(blank=True, default='', max_length=15, verbose_name='연락처')),
                ('birth_day', models.CharField(blank=True, default='', max_length=10, verbose_name='생일')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '남'), (2, '여')], default=None, null=True, verbose_name='성별')),
                ('memo', models.TextField(blank=True, default='', verbose_name='메모')),
                ('color', models.CharField(blank=True, default='', max_length=10, verbose_name='색상 마커')),
                ('is_agree_term', models.BooleanField(blank=True, default=False, verbose_name='일반 동의 여부')),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='공유 토큰')),
                ('share_expires_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='공유 만료일')),
                ('user_view_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='고객 열람 시각')),
                ('consent_overseas_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='병력 국외이전 동의 시각')),
                ('share_sent_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='공유 발송 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객',
                'db_table': 'customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, verbose_name='병명/진단')),
                ('diagnosed_at', models.CharField(blank=True, max_length=10, null=True, verbose_name='진단일')),
                ('is_inpatient', models.BooleanField(default=False, verbose_name='입원여부')),
                ('treatment_content', models.CharField(blank=True, default='', max_length=100, verbose_name='치료 내용')),
                ('hospital_name', models.CharField(blank=True, default='', max_length=100, verbose_name='병원명')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '고객 병력',
                'verbose_name_plural': '고객 병력',
                'db_table': 'customer_medical_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='태그 이름')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='색 칩')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '고객 태그',
                'verbose_name_plural': '고객 태그',
                'db_table': 'customer_tag',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('self', '본인'), ('spouse', '배우자'), ('child', '자녀'), ('parent', '부모'), ('other', '기타')], default='other', max_length=20, verbose_name='관계')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='이름')),
                ('birth_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='생년월일')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '남'), (2, '여')], null=True, verbose_name='성별')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '가족구성원',
                'verbose_name_plural': '가족구성원',
                'db_table': 'family_member',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobRiskCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sctg_cd', models.CharField(db_index=True, max_length=10, verbose_name='소분류 코드')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='직업명')),
                ('risk_grade', models.PositiveSmallIntegerField(choices=[(1, '1급'), (2, '2급'), (3, '3급'), (9, '기타')], default=9, verbose_name='위험등급')),
                ('source', models.CharField(default='meritz', max_length=20, verbose_name='출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '직업 위험등급 코드',
                'verbose_name_plural': '직업 위험등급 코드',
                'db_table': 'job_risk_code',
            },
        ),
        migrations.CreateModel(
            name='PlannerBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_key', models.CharField(db_index=True, max_length=120, verbose_name='표준 담보 키')),
                ('product_group', models.SmallIntegerField(choices=[(1, '생명'), (2, '손해'), (3, '실손'), (4, '연금저축')], verbose_name='상품군')),
                ('age_band', models.CharField(max_length=10, verbose_name='연령대')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '남'), (2, '여')], null=True, verbose_name='성별')),
                ('recommend_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='권장 하한')),
                ('recommend_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='권장 상한')),
                ('unit', models.SmallIntegerField(default=1, verbose_name='금액 단위')),
                ('baseline_source', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='기준 출처')),
                ('preset_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='프리셋 출처 라벨')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_baselines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '설계사 기준선',
                'verbose_name_plural': '설계사 기준선',
                'db_table': 'planner_baseline',
            },
        ),
        migrations.AddConstraint(
            model_name='jobriskcode',
            constraint=models.UniqueConstraint(fields=('sctg_cd', 'name'), name='uniq_jobriskcode_sctg_name'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customermedicalhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.jobriskcode', verbose_name='직업 코드(위험등급)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='customers.customertag'),
        ),
        migrations.AddField(
            model_name='consentlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='customers.customer'),
        ),
        migrations.AddConstraint(
            model_name='plannerbaseline',
            constraint=models.UniqueConstraint(fields=('owner', 'coverage_key', 'product_group', 'age_band', 'gender'), name='uniq_baseline_scope'),
        ),
        migrations.AddConstraint(
            model_name='customertag',
            constraint=models.UniqueConstraint(fields=('owner', 'label'), name='uniq_tag_owner_label'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['owner', '-created_at'], name='customer_owner_i_a676d0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['owner', 'name'], name='customer_owner_i_6a31ed_idx'),
        ),
        migrations.AddIndex(
            model_name='consentlog',
            index=models.Index(fields=['customer', 'scope'], name='consent_log_custome_878e1d_idx'),
        ),
    ]
