# Generated by Django 4.2.27 on 2026-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='리드 생성 시각'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_source',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='리드 출처'),
        ),
    ]
