# Generated by Django 4.2.27 on 2026-06-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_phase2_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to='customers.customer'),
        ),
    ]
