# Generated by Django 4.2.27 on 2026-06-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_consentlog_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentlog',
            name='subject',
            field=models.CharField(choices=[('customer_self', '고객 본인'), ('planner_attested', '설계사 기록(대리)')], default='planner_attested', max_length=20, verbose_name='동의 주체'),
        ),
    ]
