# Generated by Django 4.2.27 on 2026-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_consentlog_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_stage',
            field=models.CharField(choices=[('db', 'DB확보'), ('contact', '전화·메신저'), ('meeting', '대면상담'), ('contract', '계약')], db_index=True, default='db', max_length=10, verbose_name='영업 단계'),
        ),
    ]
