# Generated by Django 4.2.27 on 2026-06-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_sales_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_card',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards/', verbose_name='명함 이미지'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='상단 고정'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='최종 연락일'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_stage',
            field=models.CharField(choices=[('db', 'DB'), ('contact', 'TA'), ('meeting', 'FA'), ('contract', '청약')], db_index=True, default='db', max_length=10, verbose_name='영업 단계'),
        ),
    ]
