# Generated by Django 4.2.27 on 2026-06-25 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_customer_business_card_customer_is_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='항목')),
                ('is_done', models.BooleanField(default=False, verbose_name='완료')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_checklist_items', to='customers.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_checklist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '계약 체크리스트 항목',
                'verbose_name_plural': '계약 체크리스트 항목',
                'db_table': 'contract_checklist_item',
                'ordering': ['order', 'id'],
            },
        ),
    ]
