# Generated by Django 4.2.27 on 2026-06-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_contractchecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_label',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='아바타 글씨'),
        ),
    ]
