# Generated by Django 4.2.27 on 2026-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_avatar_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('introduction', '소개'), ('business_card', '명함'), ('event', '행사'), ('direct', '직접 등록'), ('self_diagnosis', '셀프진단')], default=None, max_length=30, null=True, verbose_name='리드 출처'),
        ),
    ]
