# Generated by Django 4.2.27 on 2026-06-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_consentlog_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobriskcode',
            name='alt_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='직업 약명'),
        ),
        migrations.AddField(
            model_name='jobriskcode',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='직업 설명'),
        ),
        migrations.AddField(
            model_name='jobriskcode',
            name='kidi_cd',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='KIDI 직업코드'),
        ),
        migrations.AddField(
            model_name='jobriskcode',
            name='lctg_cd',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='대분류 코드'),
        ),
        migrations.AddField(
            model_name='jobriskcode',
            name='mctg_cd',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='중분류 코드'),
        ),
        migrations.AddField(
            model_name='jobriskcode',
            name='synonym',
            field=models.TextField(blank=True, default='', verbose_name='검색어(유사·동의어, | 구분)'),
        ),
    ]
