# Generated by Django 4.2.27 on 2026-06-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_jobriskcode_alt_name_jobriskcode_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fa_reached_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='FA 최초 도달 시각'),
        ),
    ]
