# Generated by Django 4.2.27 on 2026-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_fa_reached_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', '진행중'), ('hold', '보류'), ('dormant', '휴면'), ('closed', '종료')], db_index=True, default='active', max_length=10, verbose_name='고객 상태'),
        ),
    ]
