# Generated by Django 4.2.27 on 2026-06-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0013_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('no_answer', '부재중'), ('connected', '연결'), ('appointment', '약속'), ('rejected', '거절'), ('hold', '보류')], max_length=20, verbose_name='접촉 결과')),
                ('memo', models.TextField(blank=True, default='', verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시각')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='customers.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '접촉 로그',
                'verbose_name_plural': '접촉 로그',
                'db_table': 'contact_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='contact_log_custome_ebc866_idx')],
            },
        ),
    ]
