# Generated by Django 4.2.27 on 2026-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_contactlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentlog',
            name='scope',
            field=models.CharField(choices=[('overseas_medical', '병력 국외이전 (Claude API, 미국)'), ('medical_sensitive', '민감정보(병력) 처리'), ('marketing', '마케팅 수신'), ('personal_info', '개인정보 수집·이용'), ('third_party', '제3자 제공·플랫폼 활용')], max_length=50, verbose_name='동의 범위'),
        ),
    ]
