# Generated by Django 5.2.16 on 2026-07-22 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    CustomerMemo = apps.get_model('customers', 'CustomerMemo')
    rows = []
    for customer in Customer.objects.exclude(memo='').iterator(chunk_size=500):
        if customer.memo.strip():
            rows.append(CustomerMemo(
                owner_id=customer.owner_id,
                customer_id=customer.id,
                source='legacy_migrated',
                body=customer.memo,
                occurred_at=None,
            ))
        if len(rows) == 500:
            CustomerMemo.objects.bulk_create(rows, ignore_conflicts=True, batch_size=500)
            rows = []
    if rows:
        CustomerMemo.objects.bulk_create(rows, ignore_conflicts=True, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_consentlog_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', '직접 작성'), ('ai_summary', '녹음 요약'), ('legacy_migrated', '기존 메모')], max_length=20)),
                ('body', models.TextField(max_length=10000)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='customers.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_memo',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['customer', '-created_at', '-id'], name='customer_me_custome_abeaf8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='customer_memo_body_not_empty'), models.UniqueConstraint(condition=models.Q(('source', 'legacy_migrated')), fields=('customer',), name='uniq_customer_legacy_memo')],
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
