# Generated by Django 5.2.16 on 2026-07-23

from django.db import migrations, models


def _batches(rows, size):
    batch = []
    for row in rows:
        batch.append(row)
        if len(batch) == size:
            yield batch
            batch = []
    if batch:
        yield batch


def mark_legacy_mirrors(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    CustomerMemo = apps.get_model('customers', 'CustomerMemo')
    customers = (Customer.objects.exclude(memo='').order_by('pk')
                 .values_list('pk', 'owner_id', 'memo')
                 .iterator(chunk_size=500))

    for customer_batch in _batches(customers, 500):
        customer_ids = [row[0] for row in customer_batch]
        memos_by_customer = {customer_id: [] for customer_id in customer_ids}
        memo_rows = (CustomerMemo.objects.filter(customer_id__in=customer_ids)
                     .order_by('customer_id', 'id')
                     .values_list(
                         'id', 'customer_id', 'source', 'body', 'is_legacy_mirror'))
        for memo_row in memo_rows:
            memos_by_customer[memo_row[1]].append(memo_row)

        mark_ids = []
        create_rows = []
        for customer_id, owner_id, body in customer_batch:
            clean_body = (body or '').strip()
            if not clean_body:
                continue
            memo_candidates = memos_by_customer[customer_id]
            if any(row[4] for row in memo_candidates):
                continue

            canonical = next(
                (row for row in memo_candidates if row[2] == 'legacy_migrated'),
                None,
            )
            if canonical is None:
                canonical = next(
                    (row for row in memo_candidates
                     if row[2] == 'manual' and (row[3] or '').strip() == clean_body),
                    None,
                )
            if canonical is not None:
                mark_ids.append(canonical[0])
                continue

            create_rows.append(CustomerMemo(
                owner_id=owner_id,
                customer_id=customer_id,
                source='legacy_migrated',
                body=body,
                occurred_at=None,
                is_legacy_mirror=True,
            ))

        if mark_ids:
            CustomerMemo.objects.filter(pk__in=mark_ids).update(is_legacy_mirror=True)
        if create_rows:
            CustomerMemo.objects.bulk_create(create_rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_customermemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermemo',
            name='is_legacy_mirror',
            field=models.BooleanField(
                db_default=False, default=False, editable=False),
        ),
        migrations.RunPython(mark_legacy_mirrors, migrations.RunPython.noop),
    ]
