# Generated by Django 5.2.16 on 2026-07-23

from django.db import migrations, models


def mark_legacy_mirrors(apps, schema_editor):
    CustomerMemo = apps.get_model('customers', 'CustomerMemo')
    CustomerMemo.objects.filter(source='legacy_migrated').update(is_legacy_mirror=True)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_customermemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermemo',
            name='is_legacy_mirror',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(mark_legacy_mirrors, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customermemo',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_legacy_mirror', True)),
                fields=('customer',),
                name='uniq_customer_memo_mirror',
            ),
        ),
    ]
