# Generated by Django 5.2.16 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_customermemo_is_legacy_mirror'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customermemo',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_legacy_mirror', True)),
                fields=('customer',),
                name='uniq_customer_memo_mirror',
            ),
        ),
    ]
