# Generated by Django 5.2.16 on 2026-07-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultationsummaryrun_consultationcustomerbenefit_and_more'),
        ('customers', '0020_alter_consentlog_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermemo',
            name='summary_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo', to='consultations.consultationsummaryrun'),
        ),
    ]
