# Generated by Django 5.2.16 on 2026-07-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_customermemo_summary_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentlog',
            name='scope',
            field=models.CharField(choices=[('overseas_medical', '병력 국외이전 (Claude API, 미국)'), ('medical_sensitive', '민감정보(병력) 처리'), ('marketing', '마케팅 수신'), ('personal_info', '개인정보 수집·이용'), ('third_party', '제3자 제공·플랫폼 활용'), ('consultation_recording', '상담 녹음과 원본 보관'), ('consultation_sensitive', '상담 중 민감정보 처리'), ('consultation_overseas_summary', '상담 요약을 위한 국외 처리')], max_length=50, verbose_name='동의 범위'),
        ),
    ]
