# Generated by Django 4.2.27 on 2026-06-19 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NorthStarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ocr_upload', '증권 OCR 업로드'), ('analysis_view', '분석 조회'), ('share_created', '공유링크 발급'), ('clipboard_copy', '클립보드 복사'), ('share_view', '공유뷰 열람'), ('referral_attributed', '인바운드 귀속')], max_length=40, verbose_name='이벤트 종류')),
                ('share_token', models.UUIDField(blank=True, null=True, verbose_name='공유 토큰')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='귀속 코드')),
                ('viewer_fp', models.CharField(blank=True, max_length=64, null=True, verbose_name='열람자 지문(비식별)')),
                ('channel', models.CharField(blank=True, default='', max_length=20, verbose_name='채널')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='확장 페이로드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='적재 시각')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='northstar_events', to='customers.customer', verbose_name='대상 고객')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='northstar_events', to=settings.AUTH_USER_MODEL, verbose_name='발신 설계사')),
            ],
            options={
                'verbose_name': '북극성 이벤트',
                'verbose_name_plural': '북극성 이벤트',
                'db_table': 'northstar_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='northstar_e_event_t_d2abea_idx'), models.Index(fields=['share_token'], name='northstar_e_share_t_72e5fa_idx'), models.Index(fields=['ref_code', 'event_type'], name='northstar_e_ref_cod_62b851_idx'), models.Index(fields=['sender', 'created_at'], name='northstar_e_sender__47d667_idx')],
            },
        ),
    ]
