# Generated by Django 4.2.27 on 2026-07-08 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0015_alter_consentlog_scope'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.UUIDField(blank=True, null=True, verbose_name='캡처 시점 공유 토큰')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='공유뷰 페이로드(그때 그 화면, 값 복제)')),
                ('consent_overseas', models.BooleanField(default=False, verbose_name='캡처 시점 국외이전 동의')),
                ('consent_doc_version', models.CharField(blank=True, default='', max_length=40, verbose_name='캡처 시점 동의문 버전')),
                ('consent_scopes', models.JSONField(blank=True, default=list, verbose_name='캡처 시점 유효 동의 범위')),
                ('dict_version', models.CharField(blank=True, default='', max_length=40, verbose_name='캡처 시점 정규화 사전 버전')),
                ('insurance_count', models.SmallIntegerField(default=0, verbose_name='캡처 시점 보유 보험 수')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='캡처 시각')),
                ('retention_expires_at', models.DateTimeField(db_index=True, verbose_name='자동 삭제 예정일')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_snapshots', to='customers.customer', verbose_name='대상 고객')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='설계사')),
            ],
            options={
                'verbose_name': '공유 기록',
                'verbose_name_plural': '공유 기록',
                'db_table': 'share_snapshot',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['owner', 'customer'], name='share_snaps_owner_i_827365_idx'), models.Index(fields=['retention_expires_at'], name='share_snaps_retenti_0be6b8_idx')],
            },
        ),
    ]
