# Generated by Django 4.2.27 on 2026-07-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_sharesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='northstarevent',
            name='event_type',
            field=models.CharField(choices=[('ocr_upload', '증권 OCR 업로드'), ('analysis_view', '분석 조회'), ('share_created', '공유링크 발급'), ('clipboard_copy', '클립보드 복사'), ('share_view', '공유뷰 열람'), ('referral_attributed', '인바운드 귀속'), ('cta_click', '예약 CTA 클릭')], max_length=40, verbose_name='이벤트 종류'),
        ),
    ]
