# Generated by Django 5.2.16 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_share_snapshot_token_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='northstarevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('ocr_upload', '증권 OCR 업로드'),
                    ('analysis_view', '분석 조회'),
                    ('share_created', '공유링크 발급'),
                    ('clipboard_copy', '클립보드 복사'),
                    ('share_view', '공유뷰 열람'),
                    ('referral_attributed', '인바운드 귀속'),
                    ('cta_click', '예약 CTA 클릭'),
                    ('consultation_memo_created', '상담 메모 작성'),
                    ('consultation_memo_edited', '상담 메모 수정'),
                ],
                max_length=40,
                verbose_name='이벤트 종류',
            ),
        ),
    ]
