# Generated by Django 4.2.27 on 2026-06-23 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_consentlog_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('event', '일정'), ('todo', '할일'), ('block', '차단')], default='event', max_length=10, verbose_name='종류')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('memo', models.TextField(blank=True, default='', verbose_name='메모')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='시작/마감')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='종료')),
                ('all_day', models.BooleanField(default=False, verbose_name='온종일')),
                ('is_done', models.BooleanField(default=False, verbose_name='완료')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('recur_weekday', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='반복 요일(0=월..6=일)')),
                ('recur_start_time', models.TimeField(blank=True, null=True, verbose_name='반복 차단 시작')),
                ('recur_end_time', models.TimeField(blank=True, null=True, verbose_name='반복 차단 종료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='customers.customer', verbose_name='연결 고객')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
            ],
            options={
                'verbose_name': '일정 항목',
                'verbose_name_plural': '일정 항목',
                'db_table': 'schedule_item',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['owner', 'kind', 'start_at'], name='schedule_it_owner_i_90c565_idx'), models.Index(fields=['owner', 'kind', 'recur_weekday'], name='schedule_it_owner_i_c104cf_idx')],
            },
        ),
    ]
