# Generated by Django 4.2.27 on 2026-06-25 17:56

from django.db import migrations, models


def backfill_category(apps, schema_editor):
    """기존 항목 분류 추정: todo→업무(task), 고객 연결 event→고객미팅(meeting), 그 외→기타."""
    ScheduleItem = apps.get_model('schedule', 'ScheduleItem')
    ScheduleItem.objects.filter(kind='todo').update(category='task')
    ScheduleItem.objects.filter(kind='event', customer__isnull=False).update(category='meeting')


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='anniversary_md',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='기념일(MM-DD)'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='category',
            field=models.CharField(choices=[('meeting', '고객미팅'), ('anniversary', '생일·기념일'), ('renewal', '만기·갱신'), ('task', '업무'), ('etc', '기타')], db_index=True, default='etc', max_length=12, verbose_name='분류'),
        ),
        migrations.RunPython(backfill_category, migrations.RunPython.noop),
    ]
