# Generated by Django 4.2.27 on 2026-06-19 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_response', models.JSONField(default=dict, help_text='★ PII 포함 가능. owner + 관리자만 접근.', verbose_name='폼 응답')),
                ('status', models.CharField(choices=[('pending', '예약 접수'), ('reviewing', '검토 중'), ('producing', '제작 중'), ('shipping', '발송'), ('completed', '완료'), ('cancelled', '취소')], db_index=True, default='pending', max_length=20, verbose_name='주문 상태')),
                ('admin_note', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='운송장 번호')),
                ('carrier', models.CharField(blank=True, max_length=50, verbose_name='택배사')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_orders', to=settings.AUTH_USER_MODEL, verbose_name='소유자(설계사)')),
            ],
            options={
                'verbose_name': '판촉물 주문',
                'verbose_name_plural': '판촉물 주문',
                'db_table': 'promotion_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='샘플명')),
                ('category', models.CharField(help_text='달력 / 다이어리 / 생활용품 / 기타', max_length=30, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, verbose_name='설명(재질·사이즈·납기 등)')),
                ('is_available', models.BooleanField(default=True, help_text='False = 품절·단종 → 설계사 목록에 "주문 불가" 배지.', verbose_name='주문 가능')),
                ('form_fields', models.JSONField(default=list, help_text='[{"key":str,"label":str,"type":str,"required":bool,...}]', verbose_name='폼 필드 정의')),
                ('sort_order', models.IntegerField(default=0, verbose_name='노출 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '판촉물 샘플',
                'verbose_name_plural': '판촉물 샘플',
                'db_table': 'promotion_sample',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionSampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='이미지 URL (S3)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='대표 이미지')),
                ('sort_order', models.IntegerField(default=0, verbose_name='순서')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotion.promotionsample', verbose_name='샘플')),
            ],
            options={
                'verbose_name': '샘플 이미지',
                'verbose_name_plural': '샘플 이미지',
                'db_table': 'promotion_sample_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionOrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_status', models.CharField(max_length=20, verbose_name='전이 상태')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경 시각')),
                ('note', models.TextField(blank=True, verbose_name='전이 메모')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자(관리자/설계사)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='promotion.promotionorder', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 상태 이력',
                'verbose_name_plural': '주문 상태 이력',
                'db_table': 'promotion_order_status_log',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddField(
            model_name='promotionorder',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotion.promotionsample', verbose_name='선택 샘플'),
        ),
    ]
