# Generated by Django 4.2.27 on 2026-06-25 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsample',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to='promotion/digital/', verbose_name='전자자료 파일(1회 무료 다운로드)'),
        ),
        migrations.AddField(
            model_name='promotionsample',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='전자자료'),
        ),
        migrations.CreateModel(
            name='PromotionDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=False, verbose_name='무료(1회차)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='promotion.promotionorder', verbose_name='연결 주문(2회차+)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_downloads', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='promotion.promotionsample', verbose_name='전자자료 샘플')),
            ],
            options={
                'verbose_name': '전자자료 다운로드',
                'verbose_name_plural': '전자자료 다운로드',
                'db_table': 'promotion_download',
                'ordering': ['-created_at'],
            },
        ),
    ]
