# Generated by Django 5.2.16 on 2026-07-26 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0019_customer_memo_rolling_bridge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_enabled', models.BooleanField(default=False)),
                ('ai_summary_enabled', models.BooleanField(default=False)),
                ('max_duration_seconds', models.PositiveIntegerField(default=3600)),
                ('max_bytes', models.PositiveBigIntegerField(default=104857600)),
                ('global_active_limit', models.PositiveSmallIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '상담 녹음 운영 설정',
                'db_table': 'consultation_runtime_config',
            },
        ),
        migrations.CreateModel(
            name='ConsultationPilotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_allowed', models.BooleanField(default=False)),
                ('summary_allowed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_pilot_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '상담 녹음 파일럿 계정',
                'db_table': 'consultation_pilot_access',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('uploading', 'uploading'), ('ready', 'ready'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed'), ('ambiguous', 'ambiguous'), ('deleting', 'deleting'), ('deleted', 'deleted')], db_index=True, default='uploading', max_length=20)),
                ('storage_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('multipart_upload_id', models.CharField(blank=True, default='', max_length=512)),
                ('mime_type', models.CharField(max_length=80)),
                ('codec', models.CharField(blank=True, default='', max_length=80)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('duration_ms', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, default='', max_length=40)),
                ('delete_result', models.CharField(blank=True, default='', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_recordings', to='customers.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultation_recording',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'customer', '-created_at'], name='consultatio_owner_i_b73a9a_idx'), models.Index(fields=['status', 'expires_at'], name='consultatio_status_a46995_idx')],
            },
        ),
    ]
