# Generated by Django 5.2.16 on 2026-07-26 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('customers', '0020_alter_consentlog_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consultationrecording',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'uploading')), fields=('owner', 'customer'), name='uniq_active_consultation_upload'),
        ),
    ]
