# Generated by Django 5.2.16 on 2026-07-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationrecording_uniq_active_consultation_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecording',
            name='delete_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultationrecording',
            name='last_delete_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecording',
            name='last_delete_error_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
