# Generated by Django 5.2.16 on 2026-07-26 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultationrecording_delete_attempts_and_more'),
        ('customers', '0020_alter_consentlog_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecording',
            name='client_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='consultationrecording',
            constraint=models.UniqueConstraint(condition=models.Q(('client_session_id__isnull', False)), fields=('owner', 'client_session_id'), name='uniq_consultation_client_session'),
        ),
    ]
