# Generated by Django 5.2.16 on 2026-07-26 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultationrecording_client_session_id_and_more'),
        ('customers', '0020_alter_consentlog_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSummaryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('transcribing', 'transcribing'), ('summarizing', 'summarizing'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('ambiguous', 'ambiguous'), ('cancelled', 'cancelled')], db_index=True, default='queued', max_length=20)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('attempt_uuid', models.UUIDField(default=uuid.uuid4)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('stt_provider', models.CharField(blank=True, default='', max_length=40)),
                ('stt_job_id', models.CharField(blank=True, default='', max_length=200)),
                ('summary_provider', models.CharField(blank=True, default='', max_length=40)),
                ('summary_model', models.CharField(blank=True, default='', max_length=100)),
                ('summary_reserved_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_version', models.CharField(max_length=40)),
                ('recording_consent_version', models.CharField(max_length=40)),
                ('sensitive_consent_version', models.CharField(max_length=40)),
                ('overseas_consent_version', models.CharField(max_length=40)),
                ('provider_reserved_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_seconds', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_krw', models.PositiveIntegerField(default=0)),
                ('usage_year_month', models.CharField(blank=True, default='', max_length=7)),
                ('success_count_reserved', models.PositiveSmallIntegerField(default=0)),
                ('processing_minutes_reserved', models.PositiveIntegerField(default=0)),
                ('success_reservation_released_at', models.DateTimeField(blank=True, null=True)),
                ('minute_reservation_released_at', models.DateTimeField(blank=True, null=True)),
                ('admin_compensated_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=40)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_type', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_run', to='consultations.consultationrecording')),
            ],
            options={
                'db_table': 'consultation_summary_run',
            },
        ),
        migrations.CreateModel(
            name='ConsultationCustomerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'reserved'), ('consumed', 'consumed')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_summary_benefits', to='customers.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_customer_benefits', to=settings.AUTH_USER_MODEL)),
                ('reserved_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_benefit', to='consultations.consultationsummaryrun')),
            ],
            options={
                'db_table': 'consultation_customer_benefit',
            },
        ),
        migrations.AddIndex(
            model_name='consultationsummaryrun',
            index=models.Index(fields=['status', 'lease_expires_at'], name='consultatio_status_80bdb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='consultationcustomerbenefit',
            constraint=models.UniqueConstraint(fields=('owner', 'customer'), name='uniq_consultation_customer_benefit'),
        ),
    ]
