# Generated by Django 5.2.16 on 2026-08-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_recording_notice_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationruntimeconfig',
            name='general_access_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
