# Generated by Django 4.2.27 on 2026-07-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inpa.recruiting.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('channel', models.CharField(choices=[('relationship', '개인 소개'), ('threads', 'Threads'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('saramin', '사람인'), ('jobkorea', '잡코리아'), ('inpa_content', '인파 콘텐츠')], max_length=20)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('career_band', models.CharField(choices=[('under_1', '1년 미만'), ('1_3', '1~3년'), ('3_5', '3~5년'), ('5_10', '5~10년'), ('10_plus', '10년 이상')], max_length=20)),
                ('current_affiliation', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(max_length=60)),
                ('contact_window', models.CharField(choices=[('morning', '오전'), ('afternoon', '오후'), ('evening', '저녁'), ('anytime', '언제든')], max_length=20)),
                ('submission_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('audit_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identity_ref', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('selection_status', models.CharField(choices=[('pending', '선택 대기'), ('active', '진행 중'), ('replaced', '다른 담당자 연결'), ('declined', '진행 종료')], default='active', max_length=20)),
                ('stage', models.CharField(choices=[('new', '새 지원'), ('contact', '연락'), ('conversation', '대화·면담'), ('preparing', '위촉 준비'), ('team_join', '팀 합류'), ('recontact', '다시 연락'), ('ended', '종료')], default='new', max_length=20)),
                ('next_action', models.CharField(blank=True, choices=[('call', '전화'), ('message', '메시지'), ('meeting', '미팅'), ('follow_up', '다시 확인'), ('none', '없음')], max_length=30)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('retention_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contact_opt_out_at', models.DateTimeField(blank=True, null=True)),
                ('manage_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='recruiting.recruitingcampaign')),
                ('joined_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_recruiting_candidates', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_candidates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingCopyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('headline', '첫 문장'), ('support', '정착 지원'), ('faq', '자주 묻는 질문'), ('share', '공유 문구')], max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(choices=[(1, '1주'), (4, '4주'), (8, '8주'), (13, '13주')])),
                ('due_on', models.DateField(db_index=True)),
                ('state', models.CharField(choices=[('active', '활동 중'), ('support_needed', '지원 필요'), ('stopped', '중단')], default='active', max_length=20)),
                ('blocker', models.CharField(blank=True, choices=[('customer_prospecting', '고객 발굴'), ('consultation_prep', '상담 준비'), ('product_understanding', '상품 이해'), ('work_tools', '업무 도구'), ('time_management', '시간 관리'), ('organization_adjustment', '조직 적응'), ('personal', '개인 사정'), ('none', '해당 없음')], max_length=30)),
                ('next_support', models.CharField(blank=True, choices=[('consultation_prep', '상담 준비'), ('training', '교육'), ('activity_plan', '활동 계획'), ('tool_help', '도구 도움'), ('leader_meeting', '리더 미팅'), ('schedule_only', '일정만 잡기'), ('close', '마무리')], max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_checks', to='recruiting.recruitingcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_region', models.CharField(blank=True, max_length=60)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headline_pages', to='recruiting.recruitingcopytemplate')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_page', to=settings.AUTH_USER_MODEL)),
                ('templates', models.ManyToManyField(blank=True, to='recruiting.recruitingcopytemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_published', '페이지 공개'), ('link_copied', '링크 복사'), ('page_view', '페이지 방문'), ('application_submitted', '지원 제출'), ('first_contact', '첫 연락'), ('conversation_started', '대화 시작'), ('preparing_started', '위촉 준비 시작'), ('team_join', '팀 합류'), ('settlement_completed', '정착 확인'), ('manager_promoted', '관리자 성장')], db_index=True, max_length=40)),
                ('channel', models.CharField(blank=True, choices=[('relationship', '개인 소개'), ('threads', 'Threads'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('saramin', '사람인'), ('jobkorea', '잡코리아'), ('inpa_content', '인파 콘텐츠')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[inpa.recruiting.models.validate_recruiting_event_metadata])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiting.recruitingcampaign')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiting.recruitingcandidate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='recruiting_contact', max_length=30)),
                ('doc_version', models.CharField(max_length=30)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='recruiting.recruitingcandidate')),
            ],
        ),
        migrations.AddField(
            model_name='recruitingcampaign',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='recruiting.recruitingpage'),
        ),
        migrations.CreateModel(
            name='RecruitingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_ref', models.UUIDField(db_index=True, editable=False)),
                ('event_type', models.CharField(choices=[('stage_changed', '단계 변경'), ('contact_stopped', '연락 중단'), ('leader_changed', '담당 변경'), ('team_joined', '팀 합류'), ('settlement_completed', '정착 확인'), ('candidate_purged', '정보 정리')], max_length=30)),
                ('from_stage', models.CharField(blank=True, max_length=20)),
                ('to_stage', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='recruiting.recruitingcandidate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='settlementcheck',
            constraint=models.UniqueConstraint(fields=('candidate', 'week'), name='uniq_candidate_settlement_week'),
        ),
        migrations.AddIndex(
            model_name='recruitingcandidate',
            index=models.Index(fields=['owner', 'stage', 'next_action_at'], name='recruiting__owner_i_59a306_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitingcandidate',
            index=models.Index(fields=['owner', 'phone'], name='recruiting__owner_i_a88759_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitingcandidate',
            constraint=models.UniqueConstraint(fields=('campaign', 'submission_key'), name='uniq_recruiting_campaign_submission'),
        ),
        migrations.AddConstraint(
            model_name='recruitingcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'relationship'), ('is_active', True)), fields=('page', 'channel'), name='uniq_recruiting_relationship_campaign'),
        ),
    ]
