# Generated by Django 4.2.27 on 2026-06-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_common', models.BooleanField(default=False, verbose_name='공통 유무')),
                ('insurance_type', models.SmallIntegerField(choices=[(1, '생명보험'), (2, '손해보험')], default=1)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='상품명')),
                ('contractor_name', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='계약자 이름')),
                ('insured_name', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='피보험자 이름')),
                ('is_same_insured', models.BooleanField(blank=True, default=None, null=True, verbose_name='계/피 동일')),
                ('portfolio_type', models.SmallIntegerField(choices=[(0, '템플릿'), (1, '보유'), (2, '제안')], default=0, verbose_name='포트폴리오 타입')),
                ('payment_period_type', models.SmallIntegerField(choices=[(1, '년'), (2, '년 갱신')], default=1, verbose_name='납입기간 타입')),
                ('warranty_period_type', models.SmallIntegerField(choices=[(1, '세 만기'), (2, '년 만기'), (3, '종신')], default=1, verbose_name='보장기간 타입')),
                ('payment_period', models.IntegerField(blank=True, default=None, null=True, verbose_name='납입기간')),
                ('warranty_period', models.IntegerField(blank=True, default=None, null=True, verbose_name='보장기간')),
                ('contract_date', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='계약일')),
                ('expiry_date', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='만기일')),
                ('old', models.IntegerField(blank=True, default=None, null=True, verbose_name='나이')),
                ('renewal_month', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 갱신 납입 회차')),
                ('non_renewal_month', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 비갱신 납입 회차')),
                ('monthly_assurance_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 보장 보험료')),
                ('monthly_special_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 특약 보험료')),
                ('monthly_premiums', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 납입 보험료')),
                ('monthly_contract_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 주계약 보험료')),
                ('monthly_earned_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 적립 보험료')),
                ('monthly_non_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 비갱신 보험료')),
                ('monthly_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 갱신 보험료')),
                ('total_premiums', models.FloatField(blank=True, default=None, null=True, verbose_name='총 납입 보험료')),
                ('total_renewal_premium', models.FloatField(blank=True, default=None, null=True, verbose_name='총 갱신 보험료')),
                ('total_non_renewal_premium', models.FloatField(blank=True, default=None, null=True, verbose_name='총 비갱신 보험료')),
                ('total_earned_premium', models.FloatField(blank=True, default=None, null=True, verbose_name='총 적립 보험료')),
                ('expected_due_year', models.IntegerField(blank=True, default=None, null=True, verbose_name='예상 만기 년수')),
                ('cancellation_refund', models.IntegerField(blank=True, default=None, null=True, verbose_name='혜약 환급금')),
                ('refund_type', models.SmallIntegerField(choices=[(1, '종신보험'), (2, '만기환급'), (3, '50%환급'), (4, '순수보장형')], default=1, verbose_name='환급타입')),
                ('percent_cancellation_refund', models.IntegerField(blank=True, default=None, null=True, verbose_name='혜약 환급금 퍼센트')),
                ('renewal_growth_rate', models.FloatField(blank=True, default=None, null=True, verbose_name='갱신 증가율')),
                ('renewal_special_expiry_date', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='갱신특약 만기일 날짜')),
                ('renewal_special_expiry', models.IntegerField(blank=True, default=None, null=True, verbose_name='갱신특약 만기일')),
                ('user_view_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('comment_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('custom_coverages', models.JSONField(blank=True, default=list, verbose_name='수동 담보')),
                ('share_token', models.UUIDField(blank=True, default=None, null=True, unique=True, verbose_name='공유 토큰')),
                ('share_expires_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='공유 만료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_insurance_list', to='customers.customer')),
            ],
            options={
                'verbose_name': '포트폴리오',
                'verbose_name_plural': '포트폴리오',
                'db_table': 'customer_insurance',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='보험명')),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/insurance/%Y/%m/%d/')),
                ('insurance_type', models.SmallIntegerField(choices=[(1, '생명보험'), (2, '손해보험')], default=1)),
            ],
            options={
                'verbose_name': '보험',
                'verbose_name_plural': '보험',
                'db_table': 'insurance',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(0, '공통'), (1, '생명보험'), (2, '손해보험')], default=0)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '보험 카테고리',
                'verbose_name_plural': '보험 카테고리',
                'db_table': 'insurance_category',
            },
        ),
        migrations.CreateModel(
            name='InsuranceTag',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '보험 태그',
                'verbose_name_plural': '보험 태그',
                'db_table': 'insurance_tag',
            },
        ),
        migrations.CreateModel(
            name='InsuranceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(0, '공통'), (1, '생명보험'), (2, '손해보험')], default=0)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='insurances.insurancecategory')),
            ],
            options={
                'verbose_name': '보험 서브 카테고리',
                'verbose_name_plural': '보험 서브 카테고리',
                'db_table': 'insurance_sub_category',
            },
        ),
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.SmallIntegerField(choices=[(1, 'Cart1'), (2, 'Cart2')], default=1)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('chart_based_amount', models.SmallIntegerField(blank=True, default=0, verbose_name='차트 기준 금액')),
                ('analysis_detail', models.ManyToManyField(blank=True, to='analysis.analysisdetail')),
                ('chart_detail', models.ManyToManyField(blank=True, to='analysis.chartdetail')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='insurances.insurancesubcategory')),
            ],
            options={
                'verbose_name': '보험 상세 아이템',
                'verbose_name_plural': '보험 상세 아이템',
                'db_table': 'insurance_detail',
            },
        ),
        migrations.CreateModel(
            name='CustomerInsuranceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assurance_amount', models.IntegerField(blank=True, default=None, null=True, verbose_name='보장 금액')),
                ('premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='보험료')),
                ('payment_period_type', models.SmallIntegerField(choices=[(1, '년'), (2, '세'), (3, '년 갱신')], default=1, verbose_name='납입기간 타입')),
                ('payment_period', models.IntegerField(blank=True, default=None, null=True, verbose_name='납입기간')),
                ('warranty_period_type', models.SmallIntegerField(choices=[(1, '세'), (2, '년'), (3, '날짜'), (4, '종신')], default=1, verbose_name='보증기간 타입')),
                ('warranty_period', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='보증기간')),
                ('total_renewal_premium', models.FloatField(blank=True, default=None, null=True, verbose_name='총 갱신 보험료')),
                ('total_non_renewal_premium', models.FloatField(blank=True, default=None, null=True, verbose_name='총 비갱신 보험료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.insurancedetail')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_list', to='insurances.customerinsurance')),
            ],
            options={
                'verbose_name': '고객 보험 상세',
                'verbose_name_plural': '고객 보험 상세',
                'db_table': 'customer_insurance_detail',
            },
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='insurance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurances.insurance'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='tags',
            field=models.ManyToManyField(blank=True, to='insurances.insurancetag'),
        ),
        migrations.CreateModel(
            name='CustomerInsuranceRefundSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='경과년수')),
                ('refund_amount', models.IntegerField(default=0, verbose_name='해약환급금')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_schedule', to='insurances.customerinsurance')),
            ],
            options={
                'verbose_name': '해약환급금 스케줄',
                'verbose_name_plural': '해약환급금 스케줄',
                'db_table': 'customer_insurance_refund_schedule',
                'ordering': ['year'],
                'unique_together': {('insurance', 'year')},
            },
        ),
    ]
