# Generated by Django 4.2.27 on 2026-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='current_payment_period',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='현재 납입회차'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='expected_recovery_amount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='예상 환수액(추정)'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='next_payment_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='다음 납입일'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='payment_status',
            field=models.SmallIntegerField(blank=True, choices=[(1, '정상'), (2, '연체'), (3, '납입중단')], default=None, null=True, verbose_name='납입상태'),
        ),
    ]
