# Generated by Django 4.2.27 on 2026-06-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_churn_radar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='verification',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='파싱 검증 결과'),
        ),
    ]
