# Generated by Django 4.2.27 on 2026-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_parse_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='cancelled_at',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='해지일'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='해지 여부'),
        ),
    ]
