# Generated by Django 4.2.27 on 2026-07-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0004_customerinsurance_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='company',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='보험사 코드'),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='raw_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='담보 원문명'),
        ),
    ]
