# Generated by Django 4.2.27 on 2026-07-15 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_consentlog_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0003_coverageflag'),
        ('insurances', '0005_customerinsurance_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent', models.CharField(choices=[('add', '추가'), ('replace', '교체')], max_length=12)),
                ('portfolio_type', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('queued', '대기'), ('extracting', '추출'), ('validating', '검사'), ('review_required', '검토 필요'), ('confirmed', '확인 완료'), ('failed', '실패'), ('canceled', '취소'), ('superseded', '교체됨')], db_index=True, default='queued', max_length=24)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size', models.PositiveBigIntegerField()),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('safe_display_name', models.CharField(max_length=120)),
                ('source_storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('source_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('masked_lines', models.JSONField(blank=True, default=list)),
                ('draft_payload', models.JSONField(blank=True, default=dict)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.CharField(blank=True, default='', max_length=40)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=40)),
                ('normalization_version', models.CharField(blank=True, default='', max_length=40)),
                ('attempt_uuid', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('lease_expired_count', models.PositiveSmallIntegerField(default=0)),
                ('planner_edit_count', models.PositiveIntegerField(default=0)),
                ('confirmed_coverage_count', models.PositiveIntegerField(default=0)),
                ('draft_version', models.PositiveIntegerField(default=1)),
                ('target_insurance_version', models.PositiveIntegerField(blank=True, null=True)),
                ('create_idempotency_key', models.UUIDField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('error_type', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_extraction_jobs', to='customers.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_extraction_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '증권 검토 작업',
                'verbose_name_plural': '증권 검토 작업',
                'db_table': 'insurance_extraction_job',
            },
        ),
        migrations.CreateModel(
            name='InsuranceImportRuntimeConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('per_owner_concurrency', models.PositiveSmallIntegerField(default=2)),
                ('global_concurrency', models.PositiveSmallIntegerField(default=4)),
                ('force_manual_carrier_codes', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '증권 검토 실행 설정',
                'verbose_name_plural': '증권 검토 실행 설정',
                'db_table': 'insurance_import_runtime_config',
            },
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='analysis_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='confirmation_source',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_insurances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='data_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='review_status',
            field=models.CharField(choices=[('legacy_review_required', '기존 자료 확인 필요'), ('confirmed', '확인 완료'), ('excluded', '분석 제외'), ('superseded', '교체됨')], default='legacy_review_required', max_length=32),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='analysis_detail_override',
            field=models.ManyToManyField(blank=True, related_name='insurance_case_overrides', to='analysis.analysisdetail'),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='mapping_source',
            field=models.CharField(choices=[('global', '전역 사전'), ('planner_override', '설계사 수정'), ('manual', '직접 입력')], default='global', max_length=24),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='review_reason',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='source_line_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='source_line_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='source_page',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='source_text_masked',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InsuranceImportCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('patch', '수정'), ('confirm', '확정'), ('cancel', '취소')], max_length=16)),
                ('idempotency_key', models.UUIDField()),
                ('request_sha256', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='insurances.insuranceextractionjob')),
            ],
            options={
                'verbose_name': '증권 검토 멱등 명령',
                'verbose_name_plural': '증권 검토 멱등 명령',
                'db_table': 'insurance_import_command',
            },
        ),
        migrations.CreateModel(
            name='InsuranceExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('claude', 'Claude'), ('local_regex', '로컬 규칙')], max_length=20)),
                ('model_id', models.CharField(blank=True, default='', max_length=100)),
                ('outcome', models.CharField(blank=True, default='', max_length=40)),
                ('structured_payload', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_krw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='insurances.insuranceextractionjob')),
            ],
            options={
                'verbose_name': '증권 추출 결과',
                'verbose_name_plural': '증권 추출 결과',
                'db_table': 'insurance_extraction_result',
            },
        ),
        migrations.AddField(
            model_name='insuranceextractionjob',
            name='target_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_jobs', to='insurances.customerinsurance'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='source_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_insurance', to='insurances.insuranceextractionjob'),
        ),
        migrations.AddConstraint(
            model_name='insuranceimportcommand',
            constraint=models.UniqueConstraint(fields=('job', 'operation', 'idempotency_key'), name='uniq_ins_command_key'),
        ),
        migrations.AddConstraint(
            model_name='insuranceextractionresult',
            constraint=models.UniqueConstraint(fields=('job', 'provider'), name='uniq_ins_result_job_provider'),
        ),
        migrations.AddIndex(
            model_name='insuranceextractionjob',
            index=models.Index(fields=['owner', 'customer', 'status'], name='ins_import_owner_cust_st'),
        ),
        migrations.AddIndex(
            model_name='insuranceextractionjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='ins_import_status_lease'),
        ),
        migrations.AddConstraint(
            model_name='insuranceextractionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'extracting', 'validating', 'review_required'))), fields=('owner', 'customer', 'file_sha256', 'portfolio_type'), name='uniq_active_ins_import_hash'),
        ),
        migrations.AddConstraint(
            model_name='insuranceextractionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('create_idempotency_key__isnull', False)), fields=('owner', 'create_idempotency_key'), name='uniq_ins_import_create_key'),
        ),
        migrations.AddConstraint(
            model_name='insuranceimportruntimeconfig',
            constraint=models.CheckConstraint(check=models.Q(('pk', 1)), name='insurance_import_config_pk_one'),
        ),
    ]
