# Generated by Django 4.2.27 on 2026-07-15 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurances', '0006_insurance_extraction_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceImportCreateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField()),
                ('request_sha256', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_requests', to='insurances.insuranceextractionjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_import_create_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '증권 접수 멱등 요청',
                'verbose_name_plural': '증권 접수 멱등 요청',
                'db_table': 'insurance_import_create_request',
            },
        ),
        migrations.AddConstraint(
            model_name='insuranceimportcreaterequest',
            constraint=models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='uniq_ins_import_create_request_key'),
        ),
    ]
