# Generated by Django 4.2.27 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0007_insurance_import_create_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinsurance',
            name='review_status',
            field=models.CharField(
                choices=[
                    ('draft', '직접 입력 확인 전'),
                    ('legacy_review_required', '기존 자료 확인 필요'),
                    ('confirmed', '확인 완료'),
                    ('excluded', '분석 제외'),
                    ('superseded', '교체됨'),
                ],
                default='legacy_review_required', max_length=32),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='evidence_line_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='renewal_period',
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name='갱신 주기'),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='source_candidate_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
