# Generated by Django 4.2.27 on 2026-07-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0009_customerinsurancedetail_lifetime_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceimportcreaterequest',
            name='resolution_job',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='duplicate_resolution_request',
                to='insurances.insuranceextractionjob',
            ),
        ),
    ]
