# Generated by Django 4.2.27 on 2026-07-17

from django.db import migrations, models
import django.db.models.deletion


def delete_secondary_resolution_ledgers(apps, schema_editor):
    """Make the ForeignKey rows representable by the previous OneToOne schema."""
    Request = apps.get_model('insurances', 'InsuranceImportCreateRequest')
    database = schema_editor.connection.alias
    duplicate_jobs = (
        Request.objects.using(database)
        .exclude(resolution_job_id=None)
        .values('resolution_job_id')
        .annotate(total=models.Count('pk'))
        .filter(total__gt=1)
        .order_by()
    )
    for duplicate in duplicate_jobs.iterator():
        request_ids = list(
            Request.objects.using(database)
            .filter(resolution_job_id=duplicate['resolution_job_id'])
            .order_by('created_at', 'pk')
            .values_list('pk', flat=True)
        )
        Request.objects.using(database).filter(
            pk__in=request_ids[1:],
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0010_insuranceimportcreaterequest_resolution_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceimportcreaterequest',
            name='resolution_job',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='duplicate_resolution_requests',
                to='insurances.insuranceextractionjob',
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=delete_secondary_resolution_ledgers,
        ),
    ]
