# Generated by Django 4.2.27 on 2026-07-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0011_alter_insuranceimportcreaterequest_resolution_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='review_exclusion_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='ManualInsuranceCommand',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('operation', models.CharField(
                    choices=[('confirm', '확정')], default='confirm',
                    max_length=16)),
                ('idempotency_key', models.UUIDField()),
                ('request_sha256', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(
                    blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('insurance', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='manual_review_commands',
                    to='insurances.customerinsurance')),
            ],
            options={
                'verbose_name': '직접 입력 보험 멱등 명령',
                'verbose_name_plural': '직접 입력 보험 멱등 명령',
                'db_table': 'manual_insurance_command',
            },
        ),
        migrations.AddConstraint(
            model_name='manualinsurancecommand',
            constraint=models.UniqueConstraint(
                fields=('insurance', 'operation', 'idempotency_key'),
                name='uniq_manual_ins_command_key'),
        ),
    ]
