# Generated by Django 4.2.27 on 2026-06-19 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(0, '공통'), (1, '생명보험'), (2, '손해보험')], default=0)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '분석 카테고리',
                'verbose_name_plural': '분석 카테고리',
                'db_table': 'analysis_category',
            },
        ),
        migrations.CreateModel(
            name='ChartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(0, '공통'), (1, '생명보험'), (2, '손해보험')], default=0)),
                ('chart_type', models.SmallIntegerField(choices=[(1, 'Cart1'), (2, 'Cart2')], default=1)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('chart_based_amount', models.SmallIntegerField(blank=True, default=0, verbose_name='차트 기준 금액')),
            ],
            options={
                'verbose_name': '분석 차트 아이템',
                'verbose_name_plural': '분석 차트 아이템',
                'db_table': 'chart_detail',
            },
        ),
        migrations.CreateModel(
            name='UnmatchedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.SmallIntegerField(verbose_name='보험사 코드')),
                ('raw_name', models.CharField(db_index=True, max_length=120, verbose_name='미매칭 담보 원문')),
                ('occurrence', models.IntegerField(default=1, verbose_name='발생 횟수')),
                ('sample_ctx', models.CharField(blank=True, default='', max_length=300, verbose_name='샘플 컨텍스트')),
                ('resolved', models.BooleanField(default=False, verbose_name='매핑 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '미매칭 로그',
                'verbose_name_plural': '미매칭 로그',
                'db_table': 'unmatched_log',
                'indexes': [models.Index(fields=['raw_name'], name='unmatched_l_raw_nam_d34963_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(0, '공통'), (1, '생명보험'), (2, '손해보험')], default=0)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='analysis.analysiscategory')),
            ],
            options={
                'verbose_name': '분석 서브 카테고리',
                'verbose_name_plural': '분석 서브 카테고리',
                'db_table': 'analysis_sub_category',
            },
        ),
        migrations.CreateModel(
            name='AnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('chart_based_amount', models.SmallIntegerField(blank=True, default=0, verbose_name='차트 기준 금액')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='analysis.analysissubcategory')),
            ],
            options={
                'verbose_name': '분석 상세 아이템',
                'verbose_name_plural': '분석 상세 아이템',
                'db_table': 'analysis_detail',
            },
        ),
        migrations.CreateModel(
            name='NormalizationDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.SmallIntegerField(verbose_name='보험사 코드')),
                ('raw_name', models.CharField(db_index=True, max_length=120, verbose_name='보험사 담보 원문')),
                ('source', models.SmallIntegerField(choices=[(1, 'seed'), (2, 'ocr_learned'), (3, 'admin_verified')], default=1, verbose_name='출처')),
                ('confidence', models.SmallIntegerField(default=100, verbose_name='신뢰도')),
                ('hit_count', models.IntegerField(default=0, verbose_name='매칭 누적')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('std_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analysis.analysisdetail')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_normalizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '정규화 사전',
                'verbose_name_plural': '정규화 사전',
                'db_table': 'normalization_dict',
                'indexes': [models.Index(fields=['raw_name'], name='normalizati_raw_nam_d18e4a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='normalizationdict',
            constraint=models.UniqueConstraint(fields=('company', 'raw_name'), name='uniq_norm_company_rawname'),
        ),
    ]
