# Generated by Django 4.2.27 on 2026-07-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='시드 키')),
                ('version', models.CharField(max_length=20, verbose_name='데이터 버전')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시드 마커',
                'verbose_name_plural': '시드 마커',
                'db_table': 'seed_marker',
            },
        ),
    ]
