# Generated by Django 4.2.27 on 2026-07-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_customerinsurance_company_and_more'),
        ('customers', '0015_alter_consentlog_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0002_seedmarker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name_snapshot', models.CharField(blank=True, default='', max_length=200, verbose_name='담보 원문 스냅샷')),
                ('company', models.SmallIntegerField(blank=True, null=True, verbose_name='보험사 코드')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='설계사 메모')),
                ('status', models.CharField(choices=[('open', '대기'), ('accepted', '반영'), ('rejected', '반려')], default='open', max_length=10, verbose_name='상태')),
                ('resolution_memo', models.CharField(blank=True, default='', max_length=200, verbose_name='처리 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_flags', to='analysis.analysisdetail', verbose_name='현재 매핑된 표준 담보')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_flags', to='insurances.customerinsurancedetail', verbose_name='연관 담보 케이스')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_flags', to='customers.customer', verbose_name='연관 고객')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_flags', to=settings.AUTH_USER_MODEL, verbose_name='설계사(소유자)')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_coverage_flags', to=settings.AUTH_USER_MODEL, verbose_name='처리 관리자')),
            ],
            options={
                'verbose_name': '담보 위치 확인 요청',
                'verbose_name_plural': '담보 위치 확인 요청',
                'db_table': 'coverage_flag',
                'indexes': [models.Index(fields=['status'], name='coverage_fl_status_e77a30_idx')],
            },
        ),
    ]
